
# Continue creating remaining categories and comprehensive implementation structure

remaining_categories = {
    "crop_protection": [
        {
            "id": "crop_001",
            "name": "Bayer Stressgard - Plant Growth Regulator",
            "description": "Advanced plant growth regulator for stress management. Enhances plant resilience to drought, heat, and cold stress conditions.",
            "category": "crop_protection",
            "subcategory": "growth_regulators",
            "brand": "Bayer",
            "tags": ["growth_regulator", "stress_management", "plant_vigor", "yield_increase"],
            "cropType": ["rice", "wheat", "corn", "vegetables"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 1200,
            "unit": "litre",
            "stock": 300,
            "minOrderQuantity": 0.5,
            "maxOrderQuantity": 50,
            "images": ["/images/products/stressgard.jpg"],
            "specifications": {
                "active_ingredient": "Proprietary blend",
                "concentration": "Plant available form",
                "application_rate": "2-3 litres/ha",
                "crop_types": "All crops",
                "results": "10-20% yield increase",
                "shelf_life": "2 years"
            },
            "discount": 10,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 1200,
            "purchaseCount": 350,
            "supplierRating": 4.6,
            "deliveryTime": 3,
            "certifications": ["FDA Approved", "Eco-safe"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "crop_002",
            "name": "Seaweed Extract Biostimulant",
            "description": "Natural seaweed extract containing bioactive compounds. Improves root development, nutrient uptake and crop resilience.",
            "category": "crop_protection",
            "subcategory": "biostimulants",
            "brand": "NatureCare",
            "tags": ["seaweed", "biostimulant", "natural", "root_development", "nutrient_uptake"],
            "cropType": ["all_crops"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 850,
            "unit": "litre",
            "stock": 500,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 100,
            "images": ["/images/products/seaweed-extract.jpg"],
            "specifications": {
                "source": "Arctic Seaweed",
                "solids_content": "80-85%",
                "application_rate": "3-5 litres/ha",
                "crop_types": "All crops",
                "bioactive_compounds": "Amino acids, Vitamins, Minerals",
                "shelf_life": "3 years"
            },
            "discount": 8,
            "isActive": True,
            "isFeatured": False,
            "isTrending": True,
            "viewCount": 800,
            "purchaseCount": 280,
            "supplierRating": 4.5,
            "deliveryTime": 4,
            "certifications": ["Certified Organic", "NPOP Approved"],
            "warranty": "100% natural"
        },
        {
            "id": "crop_003",
            "name": "Humic Acid Soil Conditioner",
            "description": "Premium humic acid for soil improvement and nutrient availability. Enhances cation exchange capacity and water retention.",
            "category": "crop_protection",
            "subcategory": "soil_conditioners",
            "brand": "EarthCare",
            "tags": ["humic_acid", "soil_conditioner", "cec", "water_retention", "nutrient_availability"],
            "cropType": ["all_crops"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 650,
            "unit": "kg",
            "stock": 1000,
            "minOrderQuantity": 10,
            "maxOrderQuantity": 500,
            "images": ["/images/products/humic-acid.jpg"],
            "specifications": {
                "humic_acid_content": "50%",
                "fulvic_acid_content": "10%",
                "cation_exchange_capacity": "250-300 cmol/kg",
                "application_rate": "20-30 kg/ha",
                "water_holding_capacity_improvement": "15-20%",
                "shelf_life": "3 years"
            },
            "discount": 6,
            "isActive": True,
            "isFeatured": True,
            "isTrending": False,
            "viewCount": 600,
            "purchaseCount": 200,
            "supplierRating": 4.4,
            "deliveryTime": 3,
            "certifications": ["Soil Health Certified"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "crop_004",
            "name": "Trichoderma Biofungicide Consortium",
            "description": "Beneficial fungi consortium for soil health and disease suppression. Improves plant defense mechanism and nutrient cycling.",
            "category": "crop_protection",
            "subcategory": "biocontrols",
            "brand": "BioSecure",
            "tags": ["trichoderma", "biofungicide", "beneficial_fungi", "soil_health", "disease_suppression"],
            "cropType": ["all_crops"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 720,
            "unit": "kg",
            "stock": 400,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 100,
            "images": ["/images/products/trichoderma.jpg"],
            "specifications": {
                "spore_count": "2-3 x 10^8 CFU/g",
                "application_rate": "2.5-5 kg/ha",
                "target_diseases": "Root Rot, Damping Off, Wilt",
                "soil_temperature": "15-30°C optimal",
                "moisture_requirement": "20-30%",
                "shelf_life": "12 months"
            },
            "discount": 7,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 1000,
            "purchaseCount": 320,
            "supplierRating": 4.5,
            "deliveryTime": 3,
            "certifications": ["Certified Organic", "NPOP Approved"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "crop_005",
            "name": "Bacillus Subtilis Biofertilizer",
            "description": "Beneficial bacteria for phosphate solubilization and nitrogen fixation. Improves nutrient availability and crop productivity.",
            "category": "crop_protection",
            "subcategory": "biofertilizers",
            "brand": "AgriLife",
            "tags": ["bacillus", "biofertilizer", "phosphate_solubilization", "nitrogen_fixation"],
            "cropType": ["all_crops"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 480,
            "unit": "kg",
            "stock": 800,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 200,
            "images": ["/images/products/bacillus-subtilis.jpg"],
            "specifications": {
                "cfu_count": "1-2 x 10^8 CFU/g",
                "application_rate": "2.5-5 kg/ha",
                "phosphate_solubilization": "High",
                "temperature_range": "15-35°C",
                "shelf_life": "12 months",
                "storage_temperature": "4-15°C"
            },
            "discount": 5,
            "isActive": True,
            "isFeatured": False,
            "isTrending": False,
            "viewCount": 700,
            "purchaseCount": 240,
            "supplierRating": 4.3,
            "deliveryTime": 3,
            "certifications": ["Certified Organic"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "crop_006",
            "name": "Azospirillum Biofertilizer",
            "description": "Nitrogen-fixing bacteria for cereals and grasses. Enhances nitrogen availability and plant vigor with improved root development.",
            "category": "crop_protection",
            "subcategory": "biofertilizers",
            "brand": "BioNutrients",
            "tags": ["azospirillum", "biofertilizer", "nitrogen_fixing", "cereals"],
            "cropType": ["rice", "wheat", "corn", "sugarcane"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 450,
            "unit": "kg",
            "stock": 700,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 150,
            "images": ["/images/products/azospirillum.jpg"],
            "specifications": {
                "cfu_count": "1-2 x 10^8 CFU/g",
                "application_rate": "2.5 kg/ha",
                "nitrogen_contribution": "20-30 kg N/ha",
                "temperature_range": "20-35°C",
                "shelf_life": "12 months",
                "formulation": "Peat-based"
            },
            "discount": 6,
            "isActive": True,
            "isFeatured": False,
            "isTrending": False,
            "viewCount": 650,
            "purchaseCount": 200,
            "supplierRating": 4.2,
            "deliveryTime": 3,
            "certifications": ["Certified Organic"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "crop_007",
            "name": "Rhizobium Legume Inoculant",
            "description": "Nitrogen-fixing symbiotic bacteria for legumes. Reduces nitrogen fertilizer requirement and improves crop productivity.",
            "category": "crop_protection",
            "subcategory": "biofertilizers",
            "brand": "LegumeLab",
            "tags": ["rhizobium", "biofertilizer", "legumes", "nitrogen_fixing"],
            "cropType": ["chickpea", "soybean", "peas", "beans"],
            "region": ["all_india"],
            "seasonal": True,
            "seasonStart": "june",
            "seasonEnd": "december",
            "basePrice": 380,
            "unit": "kg",
            "stock": 600,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 120,
            "images": ["/images/products/rhizobium.jpg"],
            "specifications": {
                "cfu_count": "1-2 x 10^8 CFU/g",
                "application_rate": "2.5 kg/ha",
                "nitrogen_fixation": "60-100 kg N/ha",
                "crop_specific": "Yes",
                "shelf_life": "12 months",
                "inoculation_method": "Seed treatment"
            },
            "discount": 5,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 900,
            "purchaseCount": 280,
            "supplierRating": 4.4,
            "deliveryTime": 3,
            "certifications": ["Certified Organic"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "crop_008",
            "name": "Mycorrhizal Fungi Inoculant",
            "description": "Symbiotic fungi improving nutrient uptake and water availability. Enhances plant survival rate and stress tolerance.",
            "category": "crop_protection",
            "subcategory": "biocontrols",
            "brand": "FungiCare",
            "tags": ["mycorrhizal", "fungi", "nutrient_uptake", "water_availability", "stress_tolerance"],
            "cropType": ["vegetables", "fruits", "spices"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 850,
            "unit": "kg",
            "stock": 350,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 80,
            "images": ["/images/products/mycorrhizal-fungi.jpg"],
            "specifications": {
                "spore_count": "500-1000 spores/g",
                "fungal_species": "Glomus mosseae, Rhizophagus",
                "application_rate": "10 kg/ha",
                "nutrient_uptake_improvement": "30-40%",
                "temperature_range": "15-30°C",
                "shelf_life": "18 months"
            },
            "discount": 8,
            "isActive": True,
            "isFeatured": False,
            "isTrending": True,
            "viewCount": 550,
            "purchaseCount": 150,
            "supplierRating": 4.3,
            "deliveryTime": 4,
            "certifications": ["Certified Organic"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "crop_009",
            "name": "Silicon-based Fortifier",
            "description": "Soluble silicon for crop fortification. Improves disease resistance, lodging resistance and drought tolerance.",
            "category": "crop_protection",
            "subcategory": "plant_fortifiers",
            "brand": "SiliconMax",
            "tags": ["silicon", "fortifier", "disease_resistance", "lodging_resistance"],
            "cropType": ["rice", "wheat", "corn", "sugarcane"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 620,
            "unit": "kg",
            "stock": 500,
            "minOrderQuantity": 5,
            "maxOrderQuantity": 200,
            "images": ["/images/products/silicon-fortifier.jpg"],
            "specifications": {
                "silicon_content": "10-12%",
                "solubility": "Highly soluble",
                "application_rate": "10-15 kg/ha",
                "disease_resistance": "30-40% improvement",
                "lodging_resistance": "Significant improvement",
                "shelf_life": "3 years"
            },
            "discount": 6,
            "isActive": True,
            "isFeatured": True,
            "isTrending": False,
            "viewCount": 450,
            "purchaseCount": 120,
            "supplierRating": 4.2,
            "deliveryTime": 3,
            "certifications": ["Quality Assured"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "crop_010",
            "name": "Calcium Nitrate Fortifier",
            "description": "Premium calcium source for fruit and vegetable crops. Prevents blossom-end rot and improves shelf life with high fruit quality.",
            "category": "crop_protection",
            "subcategory": "nutrient_fortifiers",
            "brand": "CalciMax",
            "tags": ["calcium", "fortifier", "blossom_end_rot", "fruit_quality"],
            "cropType": ["tomato", "apple", "stone_fruits", "vegetables"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 780,
            "unit": "kg",
            "stock": 600,
            "minOrderQuantity": 5,
            "maxOrderQuantity": 200,
            "images": ["/images/products/calcium-nitrate.jpg"],
            "specifications": {
                "calcium_content": "20%",
                "nitrogen_content": "15.5%",
                "solubility": "100%",
                "application_rate": "200-300 kg/ha",
                "blossom_end_rot_prevention": "Highly effective",
                "shelf_life": "2 years"
            },
            "discount": 5,
            "isActive": True,
            "isFeatured": False,
            "isTrending": True,
            "viewCount": 700,
            "purchaseCount": 220,
            "supplierRating": 4.4,
            "deliveryTime": 3,
            "certifications": ["Quality Assured"],
            "warranty": "Quality guaranteed"
        }
    ],
    "farm_machinery": [
        {
            "id": "mach_001",
            "name": "Power Thresher (Mini) - 2.5 HP Electric",
            "description": "Compact electric-powered thresher for small-scale grain processing. Efficient threshing with minimal grain damage.",
            "category": "farm_machinery",
            "subcategory": "grain_processing",
            "brand": "AgriMach",
            "tags": ["thresher", "mini", "electric", "grain_processing", "compact"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 35000,
            "unit": "unit",
            "stock": 60,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 25,
            "images": ["/images/products/power-thresher-mini.jpg"],
            "specifications": {
                "power": "2.5 HP Electric",
                "capacity": "100-150 kg/hour",
                "feed_type": "Manual",
                "grain_damage": "<2%",
                "weight": "80 kg",
                "noise_level": "80 dB"
            },
            "discount": 5,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 1200,
            "purchaseCount": 340,
            "supplierRating": 4.5,
            "deliveryTime": 5,
            "certifications": ["ISI Certified"],
            "warranty": "2 years"
        },
        {
            "id": "mach_002",
            "name": "Chaff Cutter (Fodder Chopper)",
            "description": "Heavy-duty chaff cutter for animal feed preparation. Cuts hay and straw into uniform pieces for better digestibility.",
            "category": "farm_machinery",
            "subcategory": "animal_feed_processing",
            "brand": "FodderMaster",
            "tags": ["chaff_cutter", "fodder_chopper", "animal_feed", "straw_cutting"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 28000,
            "unit": "unit",
            "stock": 80,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 30,
            "images": ["/images/products/chaff-cutter.jpg"],
            "specifications": {
                "power": "2 HP Diesel/Electric",
                "capacity": "200-300 kg/hour",
                "cutting_length": "5-50 mm adjustable",
                "weight": "120 kg",
                "material": "MS Body with Stainless Steel Blades"
            },
            "discount": 6,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 1400,
            "purchaseCount": 420,
            "supplierRating": 4.6,
            "deliveryTime": 4,
            "certifications": ["ISI Certified"],
            "warranty": "2 years"
        },
        {
            "id": "mach_003",
            "name": "Grain Mill (Stone) - 1 HP",
            "description": "Traditional stone mill for grinding grains and pulses. Produces uniform flour with minimal heat generation.",
            "category": "farm_machinery",
            "subcategory": "grain_milling",
            "brand": "TradiMill",
            "tags": ["grain_mill", "stone_mill", "flour_grinding", "1_hp"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 22000,
            "unit": "unit",
            "stock": 50,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 20,
            "images": ["/images/products/grain-mill.jpg"],
            "specifications": {
                "power": "1 HP Electric",
                "capacity": "50-80 kg/hour",
                "stone_diameter": "8 inches",
                "fineness": "Adjustable",
                "weight": "60 kg"
            },
            "discount": 4,
            "isActive": True,
            "isFeatured": False,
            "isTrending": False,
            "viewCount": 700,
            "purchaseCount": 180,
            "supplierRating": 4.3,
            "deliveryTime": 5,
            "certifications": ["Quality Assured"],
            "warranty": "1 year"
        },
        {
            "id": "mach_004",
            "name": "Paddy Cleaner & Grader",
            "description": "Advanced paddy cleaning and grading machine with multiple sieves. Removes impurities and grades paddy by size.",
            "category": "farm_machinery",
            "subcategory": "grain_processing",
            "brand": "PaddyTech",
            "tags": ["paddy_cleaner", "grader", "impurity_removal", "automatic"],
            "region": ["all_india"],
            "seasonal": True,
            "seasonStart": "september",
            "seasonEnd": "february",
            "basePrice": 120000,
            "unit": "unit",
            "stock": 25,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 8,
            "images": ["/images/products/paddy-cleaner.jpg"],
            "specifications": {
                "power": "5 HP Diesel/Electric",
                "capacity": "1500-2000 kg/hour",
                "cleaning_efficiency": "99%",
                "grading_levels": "4-5",
                "weight": "800 kg"
            },
            "discount": 8,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 900,
            "purchaseCount": 120,
            "supplierRating": 4.7,
            "deliveryTime": 15,
            "certifications": ["ISO Certified"],
            "warranty": "2 years"
        },
        {
            "id": "mach_005",
            "name": "Maize Sheller - Motorized",
            "description": "Efficient motorized maize sheller for grain separation from cob. Suitable for commercial maize processing.",
            "category": "farm_machinery",
            "subcategory": "grain_processing",
            "brand": "MaizeMax",
            "tags": ["maize_sheller", "motorized", "grain_separation", "commercial"],
            "region": ["all_india"],
            "seasonal": True,
            "seasonStart": "september",
            "seasonEnd": "january",
            "basePrice": 85000,
            "unit": "unit",
            "stock": 35,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 12,
            "images": ["/images/products/maize-sheller.jpg"],
            "specifications": {
                "power": "3 HP Diesel/Electric",
                "capacity": "800-1000 kg/hour",
                "breakage_rate": "<2%",
                "shelling_efficiency": "99.5%",
                "weight": "400 kg"
            },
            "discount": 7,
            "isActive": True,
            "isFeatured": False,
            "isTrending": True,
            "viewCount": 800,
            "purchaseCount": 220,
            "supplierRating": 4.6,
            "deliveryTime": 10,
            "certifications": ["ISI Certified"],
            "warranty": "2 years"
        },
        {
            "id": "mach_006",
            "name": "Seed Cleaner & Sorter",
            "description": "Precision seed cleaning and sorting machine for uniform seed quality. Essential for seed processing units.",
            "category": "farm_machinery",
            "subcategory": "seed_processing",
            "brand": "SeedTech",
            "tags": ["seed_cleaner", "sorter", "precision", "uniform_quality"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 250000,
            "unit": "unit",
            "stock": 12,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 5,
            "images": ["/images/products/seed-cleaner.jpg"],
            "specifications": {
                "power": "7.5 HP Electric",
                "capacity": "2000-3000 kg/hour",
                "cleaning_efficiency": "99.8%",
                "sorting_accuracy": "95%+",
                "weight": "2500 kg"
            },
            "discount": 10,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 600,
            "purchaseCount": 65,
            "supplierRating": 4.8,
            "deliveryTime": 20,
            "certifications": ["ISO Certified"],
            "warranty": "3 years"
        },
        {
            "id": "mach_007",
            "name": "Oil Expeller (Cold Press) - 5 HP",
            "description": "Cold-press oil extraction machine for seeds and nuts. Produces pure oil with extended shelf life.",
            "category": "farm_machinery",
            "subcategory": "oil_processing",
            "brand": "OilPress",
            "tags": ["oil_expeller", "cold_press", "oil_extraction", "5_hp"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 180000,
            "unit": "unit",
            "stock": 18,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 6,
            "images": ["/images/products/oil-expeller.jpg"],
            "specifications": {
                "power": "5 HP Diesel/Electric",
                "capacity": "100-150 kg/hour",
                "oil_recovery": "90-95%",
                "temperature": "<40°C (Cold Press)",
                "weight": "1200 kg"
            },
            "discount": 8,
            "isActive": True,
            "isFeatured": True,
            "isTrending": False,
            "viewCount": 750,
            "purchaseCount": 85,
            "supplierRating": 4.7,
            "deliveryTime": 25,
            "certifications": ["ISO Certified"],
            "warranty": "2 years"
        },
        {
            "id": "mach_008",
            "name": "Spice Grinding Mill - Automatic",
            "description": "Automated spice grinding mill for fine and coarse grinding. Maintains aroma and flavor with minimal heat.",
            "category": "farm_machinery",
            "subcategory": "spice_processing",
            "brand": "SpiceMill",
            "tags": ["spice_mill", "automatic", "grinding", "aroma_preservation"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 95000,
            "unit": "unit",
            "stock": 30,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 12,
            "images": ["/images/products/spice-mill.jpg"],
            "specifications": {
                "power": "2.5 HP Electric",
                "capacity": "150-250 kg/hour",
                "fineness": "Fine to Coarse adjustable",
                "temperature_rise": "Minimal",
                "hopper_capacity": "20 litres"
            },
            "discount": 6,
            "isActive": True,
            "isFeatured": False,
            "isTrending": True,
            "viewCount": 650,
            "purchaseCount": 145,
            "supplierRating": 4.5,
            "deliveryTime": 8,
            "certifications": ["Quality Assured"],
            "warranty": "2 years"
        },
        {
            "id": "mach_009",
            "name": "Pulp Mill - Vegetable Processing",
            "description": "Industrial pulp mill for vegetable and fruit processing. Suitable for tomato paste, puree production.",
            "category": "farm_machinery",
            "subcategory": "fruit_vegetable_processing",
            "brand": "ProPulp",
            "tags": ["pulp_mill", "vegetable_processing", "tomato_paste", "industrial"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 320000,
            "unit": "unit",
            "stock": 10,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 3,
            "images": ["/images/products/pulp-mill.jpg"],
            "specifications": {
                "power": "10 HP Electric",
                "capacity": "500-800 kg/hour",
                "material": "Stainless Steel",
                "pulp_quality": "Smooth and uniform",
                "weight": "1800 kg"
            },
            "discount": 10,
            "isActive": True,
            "isFeatured": True,
            "isTrending": False,
            "viewCount": 450,
            "purchaseCount": 42,
            "supplierRating": 4.8,
            "deliveryTime": 30,
            "certifications": ["ISO Certified"],
            "warranty": "3 years"
        },
        {
            "id": "mach_010",
            "name": "Corn Popper Machine - Commercial",
            "description": "Commercial popcorn making machine for value addition. Uniform popping with high yield.",
            "category": "farm_machinery",
            "subcategory": "food_processing",
            "brand": "PopMax",
            "tags": ["popcorn_machine", "commercial", "corn_popper", "value_addition"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 65000,
            "unit": "unit",
            "stock": 25,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 10,
            "images": ["/images/products/popcorn-machine.jpg"],
            "specifications": {
                "power": "2 HP Electric",
                "capacity": "60-100 kg/hour",
                "popping_rate": "95%+",
                "temperature_control": "Automatic",
                "weight": "400 kg"
            },
            "discount": 5,
            "isActive": True,
            "isFeatured": False,
            "isTrending": True,
            "viewCount": 550,
            "purchaseCount": 98,
            "supplierRating": 4.6,
            "deliveryTime": 12,
            "certifications": ["ISI Certified"],
            "warranty": "2 years"
        }
    ],
    "animal_husbandry": [
        {
            "id": "animal_001",
            "name": "Poultry Cage System - 3 Tier (Metal)",
            "description": "Premium 3-tier metal poultry cage system for layer birds. Durable construction with automatic feeder and waterer slots.",
            "category": "animal_husbandry",
            "subcategory": "poultry_equipment",
            "brand": "PoultryMax",
            "tags": ["poultry_cage", "3_tier", "metal", "durable", "automatic_feeders"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 18000,
            "unit": "set_of_3",
            "stock": 80,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 30,
            "images": ["/images/products/poultry-cage.jpg"],
            "specifications": {
                "tiers": "3",
                "capacity": "30-40 birds per tier",
                "material": "Galvanized Metal",
                "dimensions": "6ft x 2.5ft x 5ft",
                "feeder_slots": "Automatic",
                "waterer_slots": "Automatic"
            },
            "discount": 5,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 1300,
            "purchaseCount": 380,
            "supplierRating": 4.6,
            "deliveryTime": 7,
            "certifications": ["Quality Assured"],
            "warranty": "2 years"
        },
        {
            "id": "animal_002",
            "name": "Automatic Poultry Waterer",
            "description": "Automated gravity-fed poultry waterer system. Maintains water quality and reduces spillage.",
            "category": "animal_husbandry",
            "subcategory": "poultry_equipment",
            "brand": "WaterTech",
            "tags": ["poultry_waterer", "automatic", "gravity_fed", "water_quality"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 2500,
            "unit": "unit",
            "stock": 300,
            "minOrderQuantity": 5,
            "maxOrderQuantity": 200,
            "images": ["/images/products/poultry-waterer.jpg"],
            "specifications": {
                "capacity": "20 litres",
                "nipple_count": "12",
                "water_level": "Automatic",
                "material": "Food-grade Plastic",
                "bird_capacity": "100-150 birds"
            },
            "discount": 4,
            "isActive": True,
            "isFeatured": True,
            "isTrending": False,
            "viewCount": 850,
            "purchaseCount": 520,
            "supplierRating": 4.5,
            "deliveryTime": 2,
            "certifications": ["Quality Assured"],
            "warranty": "1 year"
        },
        {
            "id": "animal_003",
            "name": "Dairy Milking Machine - Portable (Single Unit)",
            "description": "Portable single-unit milking machine for small dairy operations. Efficient extraction with gentle pulsation.",
            "category": "animal_husbandry",
            "subcategory": "dairy_equipment",
            "brand": "MilkMax",
            "tags": ["milking_machine", "portable", "single_unit", "dairy"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 45000,
            "unit": "unit",
            "stock": 40,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 15,
            "images": ["/images/products/milking-machine.jpg"],
            "specifications": {
                "type": "Single Unit",
                "power": "1.5 HP Electric",
                "capacity": "15-20 litres per milking",
                "pulsation_rate": "60 pulsations/minute",
                "weight": "25 kg",
                "material": "Stainless Steel"
            },
            "discount": 7,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 1100,
            "purchaseCount": 280,
            "supplierRating": 4.7,
            "deliveryTime": 10,
            "certifications": ["ISO Certified"],
            "warranty": "2 years"
        },
        {
            "id": "animal_004",
            "name": "Cattle Vaccination Kit - Premium",
            "description": "Complete cattle vaccination and treatment kit with essential medicines. Suitable for small to medium farms.",
            "category": "animal_husbandry",
            "subcategory": "health_management",
            "brand": "VetCare",
            "tags": ["vaccination_kit", "cattle_health", "medicines", "premium"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 15000,
            "unit": "kit",
            "stock": 120,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 50,
            "images": ["/images/products/vaccination-kit.jpg"],
            "specifications": {
                "components": "15+ essential medicines",
                "vaccines_included": "FMD, HS, BQ",
                "treatment_tools": "Syringes, Needles",
                "storage": "Cool storage required",
                "shelf_life": "12-18 months"
            },
            "discount": 8,
            "isActive": True,
            "isFeatured": False,
            "isTrending": False,
            "viewCount": 700,
            "purchaseCount": 250,
            "supplierRating": 4.6,
            "deliveryTime": 3,
            "certifications": ["Vet Approved"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "animal_005",
            "name": "Fish Tank Aerator System",
            "description": "Efficient aeration system for fish farming ponds. Improves oxygen content and reduces ammonia levels.",
            "category": "animal_husbandry",
            "subcategory": "aquaculture",
            "brand": "AquaAir",
            "tags": ["aerator", "fish_farming", "pond_aeration", "oxygen"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 35000,
            "unit": "unit",
            "stock": 50,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 20,
            "images": ["/images/products/aerator-system.jpg"],
            "specifications": {
                "power": "2 HP Electric",
                "coverage_area": "0.5-1 hectare",
                "oxygen_transfer_rate": "1.5-2 kg/hour",
                "noise_level": "75 dB",
                "weight": "80 kg"
            },
            "discount": 6,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 900,
            "purchaseCount": 180,
            "supplierRating": 4.5,
            "deliveryTime": 7,
            "certifications": ["Quality Assured"],
            "warranty": "2 years"
        },
        {
            "id": "animal_006",
            "name": "Sheep Dip Tank - 500 Litres",
            "description": "Large capacity sheep dip tank for wool cleaning and disease prevention. Durable construction with drainage system.",
            "category": "animal_husbandry",
            "subcategory": "sheep_equipment",
            "brand": "SheepMax",
            "tags": ["dip_tank", "sheep_wool", "disease_prevention", "500L"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 28000,
            "unit": "unit",
            "stock": 30,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 10,
            "images": ["/images/products/dip-tank.jpg"],
            "specifications": {
                "capacity": "500 litres",
                "material": "MS with Epoxy Coating",
                "dimensions": "3m x 1.2m x 1.5m",
                "drainage_system": "Sump type",
                "durability": "5-7 years"
            },
            "discount": 5,
            "isActive": True,
            "isFeatured": False,
            "isTrending": False,
            "viewCount": 500,
            "purchaseCount": 95,
            "supplierRating": 4.4,
            "deliveryTime": 15,
            "certifications": ["Quality Assured"],
            "warranty": "2 years"
        },
        {
            "id": "animal_007",
            "name": "Incubator - Poultry (100 Eggs Capacity)",
            "description": "Automatic temperature and humidity controlled incubator. Ideal for small hatcheries.",
            "category": "animal_husbandry",
            "subcategory": "hatchery_equipment",
            "brand": "HatchMax",
            "tags": ["incubator", "poultry_hatchery", "100_eggs", "automatic"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 22000,
            "unit": "unit",
            "stock": 45,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 15,
            "images": ["/images/products/incubator.jpg"],
            "specifications": {
                "capacity": "100 eggs",
                "temperature_control": "Automatic",
                "humidity_control": "Automatic",
                "egg_turning": "Automatic",
                "hatching_rate": "85-90%"
            },
            "discount": 6,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 1200,
            "purchaseCount": 320,
            "supplierRating": 4.6,
            "deliveryTime": 8,
            "certifications": ["ISO Certified"],
            "warranty": "2 years"
        },
        {
            "id": "animal_008",
            "name": "Cattle Feed Mixer - Motorized (1 Ton)",
            "description": "Motorized feed mixing machine for uniform animal feed preparation. Saves time and ensures quality mix.",
            "category": "animal_husbandry",
            "subcategory": "feed_equipment",
            "brand": "FeedMix",
            "tags": ["feed_mixer", "motorized", "1_ton", "cattle"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 55000,
            "unit": "unit",
            "stock": 35,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 12,
            "images": ["/images/products/feed-mixer.jpg"],
            "specifications": {
                "capacity": "1 ton",
                "power": "2 HP Diesel/Electric",
                "mixing_time": "8-10 minutes",
                "uniformity": "99%",
                "discharge": "Gravity or Conveyor"
            },
            "discount": 7,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 1100,
            "purchaseCount": 240,
            "supplierRating": 4.7,
            "deliveryTime": 12,
            "certifications": ["ISO Certified"],
            "warranty": "2 years"
        },
        {
            "id": "animal_009",
            "name": "Beehive Frame & Brood Box Kit",
            "description": "Complete beehive setup with frames and brood box. Suitable for commercial and semi-commercial beekeeping.",
            "category": "animal_husbandry",
            "subcategory": "apiculture",
            "brand": "BeeMax",
            "tags": ["beehive", "brood_box", "frames", "beekeeping"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 8000,
            "unit": "kit",
            "stock": 200,
            "minOrderQuantity": 5,
            "maxOrderQuantity": 100,
            "images": ["/images/products/beehive-kit.jpg"],
            "specifications": {
                "frame_count": "10",
                "material": "Wood",
                "brood_box_capacity": "1 deep + 2 medium",
                "honey_production": "40-60 kg/year",
                "durability": "5-7 years"
            },
            "discount": 5,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 850,
            "purchaseCount": 420,
            "supplierRating": 4.5,
            "deliveryTime": 5,
            "certifications": ["Quality Assured"],
            "warranty": "1 year"
        },
        {
            "id": "animal_010",
            "name": "Artificial Insemination Kit - Cattle",
            "description": "Complete AI kit for cattle breeding with storage and application tools. Includes training manual.",
            "category": "animal_husbandry",
            "subcategory": "breeding_equipment",
            "brand": "BreedTech",
            "tags": ["ai_kit", "artificial_insemination", "cattle_breeding"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 12000,
            "unit": "kit",
            "stock": 60,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 25,
            "images": ["/images/products/ai-kit.jpg"],
            "specifications": {
                "components": "Insemination gun, Sheaths, Storage vial",
                "storage_temperature": "-196°C in liquid nitrogen",
                "success_rate": "70-80%",
                "shelf_life": "Indefinite when stored",
                "training": "Included manual"
            },
            "discount": 6,
            "isActive": True,
            "isFeatured": False,
            "isTrending": True,
            "viewCount": 650,
            "purchaseCount": 180,
            "supplierRating": 4.5,
            "deliveryTime": 4,
            "certifications": ["Vet Approved"],
            "warranty": "1 year"
        }
    ],
    "dairy_inputs": [
        {
            "id": "dairy_001",
            "name": "Premium Buffalo Cattle Feed - Concentrate Mix",
            "description": "Balanced nutrition concentrate for dairy buffalo with 18% crude protein. Improves milk yield and animal health.",
            "category": "dairy_inputs",
            "subcategory": "dairy_feed",
            "brand": "DairyFeed Pro",
            "tags": ["buffalo_feed", "concentrate", "protein_rich", "milk_yield"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 520,
            "unit": "bag_50kg",
            "stock": 2000,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 500,
            "images": ["/images/products/buffalo-feed.jpg"],
            "specifications": {
                "crude_protein": "18%",
                "crude_fat": "4%",
                "crude_fiber": "8%",
                "calcium": "1.2%",
                "phosphorus": "0.8%",
                "energy_value": "2.8 KCAL/g"
            },
            "discount": 4,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 2200,
            "purchaseCount": 1100,
            "supplierRating": 4.7,
            "deliveryTime": 2,
            "certifications": ["Feed Quality Certified"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "dairy_002",
            "name": "Cow Cattle Feed - Green Pasture Mix",
            "description": "Complete balanced feed for dairy cows with natural green ingredients. Promotes milk production and overall health.",
            "category": "dairy_inputs",
            "subcategory": "dairy_feed",
            "brand": "GreenFarm Dairy",
            "tags": ["cow_feed", "green_pasture", "complete_feed", "balanced_nutrition"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 480,
            "unit": "bag_50kg",
            "stock": 2500,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 800,
            "images": ["/images/products/cow-feed.jpg"],
            "specifications": {
                "crude_protein": "16-17%",
                "crude_fat": "3.5%",
                "crude_fiber": "10%",
                "calcium": "1.1%",
                "phosphorus": "0.75%",
                "digestibility": "High"
            },
            "discount": 3,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 2500,
            "purchaseCount": 1400,
            "supplierRating": 4.8,
            "deliveryTime": 2,
            "certifications": ["Feed Quality Certified"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "dairy_003",
            "name": "Mineral Supplement - Dairy Animal Health",
            "description": "Comprehensive mineral premix for dairy animals including trace elements. Prevents metabolic diseases.",
            "category": "dairy_inputs",
            "subcategory": "supplements",
            "brand": "MineralCare",
            "tags": ["mineral_supplement", "trace_elements", "metabolic_health", "dairy"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 680,
            "unit": "kg",
            "stock": 800,
            "minOrderQuantity": 5,
            "maxOrderQuantity": 200,
            "images": ["/images/products/mineral-supplement.jpg"],
            "specifications": {
                "calcium": "22%",
                "phosphorus": "12%",
                "magnesium": "3%",
                "trace_elements": "Cu, Zn, Fe, Mn, Co, I, Se",
                "application_rate": "50-100 g/animal/day",
                "shelf_life": "2 years"
            },
            "discount": 6,
            "isActive": True,
            "isFeatured": True,
            "isTrending": False,
            "viewCount": 900,
            "purchaseCount": 320,
            "supplierRating": 4.6,
            "deliveryTime": 3,
            "certifications": ["Quality Assured"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "dairy_004",
            "name": "Probiotic Supplement - Dairy Animal Digestion",
            "description": "Advanced probiotic formula for rumen health and digestion. Improves nutrient absorption and milk composition.",
            "category": "dairy_inputs",
            "subcategory": "supplements",
            "brand": "ProBiotix",
            "tags": ["probiotic", "rumen_health", "digestion", "nutrient_absorption"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 920,
            "unit": "kg",
            "stock": 600,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 150,
            "images": ["/images/products/probiotic-supplement.jpg"],
            "specifications": {
                "bacterial_count": "1-2 x 10^9 CFU/g",
                "strains": "Lactobacillus, Bacillus, Yeast",
                "application_rate": "10-20 g/animal/day",
                "feed_efficiency_improvement": "8-12%",
                "shelf_life": "18 months"
            },
            "discount": 7,
            "isActive": True,
            "isFeatured": False,
            "isTrending": True,
            "viewCount": 750,
            "purchaseCount": 240,
            "supplierRating": 4.5,
            "deliveryTime": 3,
            "certifications": ["Quality Assured"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "dairy_005",
            "name": "Milk Enhancer - Galacto-Supporting Formula",
            "description": "Specialized feed additive to support lactation and milk yield. Increases lactose content and milk volume.",
            "category": "dairy_inputs",
            "subcategory": "supplements",
            "brand": "LactoPro",
            "tags": ["milk_enhancer", "lactation_support", "milk_yield", "lactose"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 1100,
            "unit": "kg",
            "stock": 500,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 100,
            "images": ["/images/products/milk-enhancer.jpg"],
            "specifications": {
                "beta_glucans": "High",
                "amino_acids": "Essential mix",
                "application_rate": "50-100 g/animal/day",
                "milk_yield_increase": "10-15%",
                "lactose_improvement": "5-7%",
                "shelf_life": "2 years"
            },
            "discount": 8,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 1100,
            "purchaseCount": 380,
            "supplierRating": 4.7,
            "deliveryTime": 3,
            "certifications": ["Quality Assured"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "dairy_006",
            "name": "Mastitis Prevention Supplement",
            "description": "Immunomodulatory supplement for mastitis prevention. Contains antioxidants and immune-supporting nutrients.",
            "category": "dairy_inputs",
            "subcategory": "health_management",
            "brand": "MastitisGuard",
            "tags": ["mastitis_prevention", "immune_support", "antioxidant", "udder_health"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 850,
            "unit": "kg",
            "stock": 700,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 150,
            "images": ["/images/products/mastitis-prevention.jpg"],
            "specifications": {
                "selenium": "High",
                "vitamin_e": "High",
                "zinc": "Optimal level",
                "antioxidants": "Premium blend",
                "application_rate": "50 g/animal/day",
                "prevention_effectiveness": "85-90%"
            },
            "discount": 6,
            "isActive": True,
            "isFeatured": True,
            "isTrending": False,
            "viewCount": 650,
            "purchaseCount": 220,
            "supplierRating": 4.6,
            "deliveryTime": 3,
            "certifications": ["Quality Assured"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "dairy_007",
            "name": "Silage Additive - Fermentation Enhancer",
            "description": "Enzymatic silage additive for better fermentation and preservation. Improves silage quality and nutritional value.",
            "category": "dairy_inputs",
            "subcategory": "feed_additives",
            "brand": "SilageMax",
            "tags": ["silage_additive", "fermentation", "preservation", "nutritional_value"],
            "region": ["all_india"],
            "seasonal": True,
            "seasonStart": "june",
            "seasonEnd": "september",
            "basePrice": 580,
            "unit": "litre",
            "stock": 1200,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 300,
            "images": ["/images/products/silage-additive.jpg"],
            "specifications": {
                "enzyme_activity": "High",
                "application_rate": "5-10 litres/ton",
                "fermentation_time": "Reduced by 40%",
                "mold_inhibition": "Excellent",
                "shelf_life": "2 years"
            },
            "discount": 5,
            "isActive": True,
            "isFeatured": False,
            "isTrending": True,
            "viewCount": 800,
            "purchaseCount": 280,
            "supplierRating": 4.4,
            "deliveryTime": 2,
            "certifications": ["Quality Assured"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "dairy_008",
            "name": "Acidifier Feed Additive - Digestive Health",
            "description": "Organic acid based acidifier for rumen health maintenance. Reduces pH and prevents acidosis.",
            "category": "dairy_inputs",
            "subcategory": "feed_additives",
            "brand": "AcidPro",
            "tags": ["acidifier", "rumen_health", "digestive", "acidosis_prevention"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 720,
            "unit": "kg",
            "stock": 600,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 200,
            "images": ["/images/products/acidifier.jpg"],
            "specifications": {
                "active_acids": "Formic + Propionic",
                "application_rate": "5-10 kg/ton feed",
                "ph_reduction": "0.5-1.0 units",
                "feed_efficiency": "5-8% improvement",
                "shelf_life": "2 years"
            },
            "discount": 5,
            "isActive": True,
            "isFeatured": False,
            "isTrending": False,
            "viewCount": 550,
            "purchaseCount": 180,
            "supplierRating": 4.3,
            "deliveryTime": 3,
            "certifications": ["Quality Assured"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "dairy_009",
            "name": "Vitamin Premix - Complete Dairy Nutrition",
            "description": "Complete vitamin and mineral premix designed specifically for dairy animals. Supports lactation and immune function.",
            "category": "dairy_inputs",
            "subcategory": "supplements",
            "brand": "VitaDairy",
            "tags": ["vitamin_premix", "complete_nutrition", "dairy_specific", "immune_support"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 950,
            "unit": "kg",
            "stock": 800,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 200,
            "images": ["/images/products/vitamin-premix.jpg"],
            "specifications": {
                "vitamin_a": "10,00,000 IU/kg",
                "vitamin_d3": "2,00,000 IU/kg",
                "vitamin_e": "2000 IU/kg",
                "vitamin_b_complex": "Complete",
                "application_rate": "10-20 g/animal/day",
                "shelf_life": "18 months"
            },
            "discount": 7,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 950,
            "purchaseCount": 320,
            "supplierRating": 4.6,
            "deliveryTime": 3,
            "certifications": ["Quality Assured"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "dairy_010",
            "name": "Transition Diet - Peripartum Nutrition",
            "description": "Specialized transition diet for peripartum cows (3 weeks before-after calving). Prevents metabolic stress.",
            "category": "dairy_inputs",
            "subcategory": "dairy_feed",
            "brand": "TransitionCare",
            "tags": ["transition_diet", "peripartum", "metabolic_stress", "specialized"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 680,
            "unit": "bag_40kg",
            "stock": 400,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 100,
            "images": ["/images/products/transition-diet.jpg"],
            "specifications": {
                "crude_protein": "14-16%",
                "energy_balance": "Negative to low positive",
                "anionic_salts": "Optimal level",
                "calcium_phosphorus_ratio": "1.5-2.0",
                "dmhb": "Included",
                "feeding_duration": "3 weeks peripartum"
            },
            "discount": 8,
            "isActive": True,
            "isFeatured": True,
            "isTrending": False,
            "viewCount": 600,
            "purchaseCount": 150,
            "supplierRating": 4.5,
            "deliveryTime": 4,
            "certifications": ["Dairy Specialist Approved"],
            "warranty": "Quality guaranteed"
        }
    ]
}

# Add new categories to the database
for category, products in remaining_categories.items():
    agricultural_database[category] = products

# Create comprehensive CSV with all products
all_products_data = []
for category, products in agricultural_database.items():
    for product in products:
        product_row = {
            'id': product['id'],
            'name': product['name'],
            'category': product['category'],
            'brand': product['brand'],
            'basePrice': product['basePrice'],
            'unit': product['unit'],
            'discount': product['discount'],
            'supplierRating': product['supplierRating'],
            'isFeatured': product['isFeatured'],
            'isTrending': product['isTrending']
        }
        all_products_data.append(product_row)

df_complete = pd.DataFrame(all_products_data)
print(f"✓ Complete Database with 9 Categories Created Successfully!")
print(f"\n{'='*70}")
print(f"AGRICULTURAL PRODUCTS DATABASE SUMMARY")
print(f"{'='*70}")
print(f"\nTotal Products: {len(all_products_data)}")
print(f"\nCategory Breakdown:")
for cat in agricultural_database.keys():
    count = len(agricultural_database[cat])
    total_price = sum([p['basePrice'] for p in agricultural_database[cat]])
    avg_price = total_price / count
    print(f"  • {cat.upper():20s}: {count:2d} products | Avg Price: ₹{avg_price:,.0f}")

print(f"\nPrice Range by Category:")
for cat in agricultural_database.keys():
    prices = [p['basePrice'] for p in agricultural_database[cat]]
    print(f"  • {cat.upper():20s}: ₹{min(prices):>10,.0f} - ₹{max(prices):>10,.0f}")

print(f"\n{'='*70}")
