
import json

# Comprehensive Agricultural Products Database for All 9 Categories
agricultural_database = {
    "seeds": [
        {
            "id": "seed_001",
            "name": "Pusa Basmati 1121 Rice Seeds - IARI",
            "description": "Premium aromatic basmati rice variety with extra-long grains and excellent cooking quality. Highest foreign exchange earner variety with superior grain elongation after cooking.",
            "category": "seeds",
            "subcategory": "rice_seeds",
            "brand": "IARI",
            "tags": ["basmati", "pusa_1121", "aromatic", "export_quality", "premium", "kharif"],
            "cropType": ["rice"],
            "region": ["north_india", "punjab", "haryana", "uttar_pradesh"],
            "seasonal": True,
            "seasonStart": "june",
            "seasonEnd": "october",
            "basePrice": 850,
            "unit": "kg",
            "stock": 1500,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 500,
            "images": ["/images/products/pusa-basmati-1121.jpg"],
            "specifications": {
                "yield_potential": "4.6 t/ha",
                "maturity_days": "135-140",
                "grain_length": "8.5-9.5 mm",
                "disease_resistance": "Bacterial Blight",
                "protein_content": "7-8%",
                "germination_rate": "85% minimum"
            },
            "discount": 8,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 2500,
            "purchaseCount": 850,
            "supplierRating": 4.8,
            "deliveryTime": 3,
            "certifications": ["Seed Certification", "ISO 9001", "GI Tag"],
            "warranty": "1 year germination guarantee"
        },
        {
            "id": "seed_002",
            "name": "HI 1544 (Purna) Wheat Seeds - IARI",
            "description": "Premium quality wheat variety with amber colored hard grains and excellent chapati quality. High protein content with strong disease resistance to rust.",
            "category": "seeds",
            "subcategory": "wheat_seeds",
            "brand": "IARI",
            "tags": ["wheat", "hi_1544", "purna", "high_protein", "rust_resistant", "rabi"],
            "cropType": ["wheat"],
            "region": ["central_india", "madhya_pradesh", "maharashtra"],
            "seasonal": True,
            "seasonStart": "november",
            "seasonEnd": "march",
            "basePrice": 650,
            "unit": "kg",
            "stock": 2500,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 1000,
            "images": ["/images/products/hi-1544-wheat.jpg"],
            "specifications": {
                "yield_potential": "4.8-5.2 t/ha",
                "maturity_days": "115-120",
                "grain_type": "Amber, Hard, Roundish",
                "disease_resistance": "Brown & Black Rust",
                "protein_content": "11-12%",
                "germination_rate": "90% minimum"
            },
            "discount": 5,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 3200,
            "purchaseCount": 1200,
            "supplierRating": 4.7,
            "deliveryTime": 2,
            "certifications": ["Seed Certification", "PPVFRA Registered"],
            "warranty": "1 year germination guarantee"
        },
        {
            "id": "seed_003",
            "name": "DEKALB 9208 Hybrid Maize Seeds - Bayer",
            "description": "High-yielding maize hybrid with uniform cobs, shiny grains and excellent plant strength. Suitable for both kharif and spring planting with stable yields.",
            "category": "seeds",
            "subcategory": "maize_seeds",
            "brand": "Bayer",
            "tags": ["maize", "corn", "dekalb", "hybrid", "high_yield", "kharif"],
            "cropType": ["maize", "corn"],
            "region": ["all_india", "maharashtra", "karnataka", "madhya_pradesh"],
            "seasonal": True,
            "seasonStart": "june",
            "seasonEnd": "september",
            "basePrice": 720,
            "unit": "kg",
            "stock": 1800,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 300,
            "images": ["/images/products/dekalb-9208-maize.jpg"],
            "specifications": {
                "yield_potential": "9.0-10.0 t/ha",
                "maturity_days": "100-110",
                "grain_type": "Flint, Yellow",
                "disease_resistance": "Turcicum Leaf Blight",
                "protein_content": "9-10%",
                "germination_rate": "90% minimum"
            },
            "discount": 7,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 2800,
            "purchaseCount": 950,
            "supplierRating": 4.6,
            "deliveryTime": 3,
            "certifications": ["Seed Certification", "ISO 9001"],
            "warranty": "Germination guarantee"
        },
        {
            "id": "seed_004",
            "name": "JS 335 Soybean Seeds - JNKVV",
            "description": "Most popular soybean variety in India with high oil and protein content. Resistant to yellow mosaic virus and suitable for central zone cultivation.",
            "category": "seeds",
            "subcategory": "soybean_seeds",
            "brand": "JNKVV",
            "tags": ["soybean", "js_335", "high_protein", "yellow_seeds", "kharif"],
            "cropType": ["soybean"],
            "region": ["central_india", "madhya_pradesh", "maharashtra", "rajasthan"],
            "seasonal": True,
            "seasonStart": "june",
            "seasonEnd": "september",
            "basePrice": 580,
            "unit": "kg",
            "stock": 3000,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 500,
            "images": ["/images/products/js-335-soybean.jpg"],
            "specifications": {
                "yield_potential": "2.5-3.0 t/ha",
                "maturity_days": "90-95",
                "seed_color": "Yellow",
                "disease_resistance": "Yellow Mosaic Virus, Girdle Beetle",
                "protein_content": "38-40%",
                "oil_content": "18-19%",
                "germination_rate": "85% minimum"
            },
            "discount": 6,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 2400,
            "purchaseCount": 1100,
            "supplierRating": 4.5,
            "deliveryTime": 2,
            "certifications": ["Seed Certification"],
            "warranty": "Germination guarantee"
        },
        {
            "id": "seed_005",
            "name": "RCH 134 Bt Cotton Hybrid Seeds",
            "description": "Widely adopted Bt cotton hybrid in Telangana with excellent bollworm resistance. Produces uniform fiber with moderate lint percentage and high yield stability.",
            "category": "seeds",
            "subcategory": "cotton_seeds",
            "brand": "Rasi Seeds",
            "tags": ["cotton", "bt_cotton", "rch_134", "bollworm_resistant", "kharif"],
            "cropType": ["cotton"],
            "region": ["south_india", "telangana", "andhra_pradesh", "karnataka"],
            "seasonal": True,
            "seasonStart": "may",
            "seasonEnd": "august",
            "basePrice": 920,
            "unit": "packet_450g",
            "stock": 2000,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 200,
            "images": ["/images/products/rch-134-cotton.jpg"],
            "specifications": {
                "yield_potential": "500-650 kg/acre",
                "maturity_days": "130-140",
                "fiber_quality": "Uniform, Medium Staple",
                "pest_resistance": "Pink Bollworm, American Bollworm",
                "ginning_outturn": "34-36%",
                "germination_rate": "85% minimum"
            },
            "discount": 10,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 3500,
            "purchaseCount": 1400,
            "supplierRating": 4.7,
            "deliveryTime": 3,
            "certifications": ["Bt Cotton Approved", "Seed Certification"],
            "warranty": "Germination guarantee"
        },
        {
            "id": "seed_006",
            "name": "Pusa 10216 Chickpea Seeds - IARI",
            "description": "Drought tolerant chickpea variety developed through molecular breeding. 11% higher yield than Pusa 372 under moisture stress with excellent grain quality.",
            "category": "seeds",
            "subcategory": "pulse_seeds",
            "brand": "IARI",
            "tags": ["chickpea", "chana", "pusa_10216", "drought_tolerant", "rabi"],
            "cropType": ["chickpea", "pulses"],
            "region": ["central_india", "madhya_pradesh", "maharashtra", "gujarat"],
            "seasonal": True,
            "seasonStart": "october",
            "seasonEnd": "december",
            "basePrice": 680,
            "unit": "kg",
            "stock": 1200,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 400,
            "images": ["/images/products/pusa-10216-chickpea.jpg"],
            "specifications": {
                "yield_potential": "1.4-1.5 t/ha",
                "maturity_days": "110",
                "seed_weight": "22.2g/100 seeds",
                "disease_resistance": "Fusarium Wilt, Dry Root Rot",
                "protein_content": "20-22%",
                "germination_rate": "85% minimum"
            },
            "discount": 5,
            "isActive": True,
            "isFeatured": True,
            "isTrending": False,
            "viewCount": 1800,
            "purchaseCount": 650,
            "supplierRating": 4.6,
            "deliveryTime": 3,
            "certifications": ["Seed Certification", "Genomics-Assisted Breeding"],
            "warranty": "Germination guarantee"
        },
        {
            "id": "seed_007",
            "name": "Swarna Rice Seeds (MTU 7029)",
            "description": "Popular non-basmati rice variety with low glycemic index and excellent nutritional value. Medium grain with good cooking quality and disease resistance.",
            "category": "seeds",
            "subcategory": "rice_seeds",
            "brand": "ICAR-NRRI",
            "tags": ["rice", "swarna", "non_basmati", "medium_grain", "kharif"],
            "cropType": ["rice"],
            "region": ["east_india", "west_bengal", "odisha", "andhra_pradesh"],
            "seasonal": True,
            "seasonStart": "june",
            "seasonEnd": "october",
            "basePrice": 520,
            "unit": "kg",
            "stock": 2200,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 800,
            "images": ["/images/products/swarna-rice.jpg"],
            "specifications": {
                "yield_potential": "5.0-5.5 t/ha",
                "maturity_days": "140-145",
                "grain_length": "5.0-5.6 mm",
                "disease_resistance": "Blast, Brown Spot",
                "protein_content": "7-8%",
                "germination_rate": "85% minimum"
            },
            "discount": 4,
            "isActive": True,
            "isFeatured": False,
            "isTrending": True,
            "viewCount": 2100,
            "purchaseCount": 900,
            "supplierRating": 4.5,
            "deliveryTime": 2,
            "certifications": ["Seed Certification"],
            "warranty": "Germination guarantee"
        },
        {
            "id": "seed_008",
            "name": "JS 95-60 Soybean Seeds - JNKVV",
            "description": "Photo-insensitive soybean variety suitable for multiple agro-climatic zones. Good oil content and disease resistance with consistent performance.",
            "category": "seeds",
            "subcategory": "soybean_seeds",
            "brand": "JNKVV",
            "tags": ["soybean", "js_95_60", "photoinsensitive", "yellow_seeds", "kharif"],
            "cropType": ["soybean"],
            "region": ["central_india", "madhya_pradesh", "maharashtra"],
            "seasonal": True,
            "seasonStart": "june",
            "seasonEnd": "september",
            "basePrice": 560,
            "unit": "kg",
            "stock": 1600,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 400,
            "images": ["/images/products/js-95-60-soybean.jpg"],
            "specifications": {
                "yield_potential": "2.3-2.8 t/ha",
                "maturity_days": "82-88",
                "seed_color": "Yellow",
                "disease_resistance": "Rust, Bacterial Pustule",
                "protein_content": "38-40%",
                "oil_content": "18-20%",
                "germination_rate": "85% minimum"
            },
            "discount": 5,
            "isActive": True,
            "isFeatured": False,
            "isTrending": False,
            "viewCount": 1400,
            "purchaseCount": 520,
            "supplierRating": 4.4,
            "deliveryTime": 2,
            "certifications": ["Seed Certification"],
            "warranty": "Germination guarantee"
        },
        {
            "id": "seed_009",
            "name": "MRC 7918 Bt Cotton Hybrid Seeds",
            "description": "Premium Bt cotton hybrid for Western Maharashtra with strong fiber quality and high yield potential. Suitable for both irrigated and rainfed systems.",
            "category": "seeds",
            "subcategory": "cotton_seeds",
            "brand": "Mahyco",
            "tags": ["cotton", "bt_cotton", "mrc_7918", "fiber_quality", "kharif"],
            "cropType": ["cotton"],
            "region": ["west_india", "maharashtra", "gujarat"],
            "seasonal": True,
            "seasonStart": "may",
            "seasonEnd": "august",
            "basePrice": 950,
            "unit": "packet_450g",
            "stock": 1500,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 150,
            "images": ["/images/products/mrc-7918-cotton.jpg"],
            "specifications": {
                "yield_potential": "550-700 kg/acre",
                "maturity_days": "130-140",
                "fiber_quality": "Superior, Medium Staple",
                "pest_resistance": "Bollworm Complex",
                "ginning_outturn": "35-37%",
                "germination_rate": "85% minimum"
            },
            "discount": 8,
            "isActive": True,
            "isFeatured": True,
            "isTrending": False,
            "viewCount": 1900,
            "purchaseCount": 720,
            "supplierRating": 4.6,
            "deliveryTime": 3,
            "certifications": ["Bt Cotton Approved", "Seed Certification"],
            "warranty": "Germination guarantee"
        },
        {
            "id": "seed_010",
            "name": "DBW 222 (Karan Narendra) Wheat Seeds - IIWBR",
            "description": "High-yielding wheat variety for timely sown irrigated conditions in North Western Plains. Excellent rust resistance and good chapati quality.",
            "category": "seeds",
            "subcategory": "wheat_seeds",
            "brand": "ICAR-IIWBR",
            "tags": ["wheat", "dbw_222", "karan_narendra", "rust_resistant", "rabi"],
            "cropType": ["wheat"],
            "region": ["north_india", "punjab", "haryana", "uttar_pradesh"],
            "seasonal": True,
            "seasonStart": "november",
            "seasonEnd": "march",
            "basePrice": 620,
            "unit": "kg",
            "stock": 2000,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 800,
            "images": ["/images/products/dbw-222-wheat.jpg"],
            "specifications": {
                "yield_potential": "5.5-6.0 t/ha",
                "maturity_days": "145-150",
                "grain_type": "Amber, Medium Bold",
                "disease_resistance": "Yellow, Brown & Black Rust",
                "protein_content": "11-12%",
                "germination_rate": "90% minimum"
            },
            "discount": 6,
            "isActive": True,
            "isFeatured": False,
            "isTrending": True,
            "viewCount": 1700,
            "purchaseCount": 680,
            "supplierRating": 4.5,
            "deliveryTime": 2,
            "certifications": ["Seed Certification", "ISO 9001"],
            "warranty": "Germination guarantee"
        }
    ],
    "fertilizers": [
        {
            "id": "fert_001",
            "name": "DAP (Di-Ammonium Phosphate) - IFFCO",
            "description": "Essential primary nutrient fertilizer containing 18% nitrogen and 46% phosphorus. Highly soluble and suitable for all crops with fast nutrient availability.",
            "category": "fertilizers",
            "subcategory": "phosphate_fertilizers",
            "brand": "IFFCO",
            "tags": ["dap", "phosphorus", "nitrogen", "primary_nutrient", "granular"],
            "cropType": ["rice", "wheat", "corn", "soybean", "cotton", "pulses"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 750,
            "unit": "bag_50kg",
            "stock": 5000,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 1000,
            "images": ["/images/products/dap-fertilizer.jpg"],
            "specifications": {
                "nitrogen_content": "18%",
                "phosphorus_content": "46%",
                "solubility": "Highly soluble",
                "soil_type": "All types",
                "application_rate": "100-150 kg/ha",
                "moisture_content": "2.5% maximum"
            },
            "discount": 3,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 4500,
            "purchaseCount": 2200,
            "supplierRating": 4.8,
            "deliveryTime": 2,
            "certifications": ["Ministry of Chemicals & Fertilizers Approved"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "fert_002",
            "name": "Urea (Carbamide) - National Fertilizers Limited",
            "description": "Highest nitrogen content (46%) among solid nitrogenous fertilizers. Highly soluble, cost-effective and universally applicable for all crops.",
            "category": "fertilizers",
            "subcategory": "nitrogen_fertilizers",
            "brand": "National Fertilizers Limited",
            "tags": ["urea", "nitrogen", "granular", "highest_nitrogen", "cost_effective"],
            "cropType": ["rice", "wheat", "corn", "sugarcane", "vegetables"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 620,
            "unit": "bag_50kg",
            "stock": 8000,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 2000,
            "images": ["/images/products/urea-fertilizer.jpg"],
            "specifications": {
                "nitrogen_content": "46%",
                "phosphorus_content": "0%",
                "potassium_content": "0%",
                "solubility": "Highly soluble",
                "application_rate": "100-250 kg/ha",
                "moisture_content": "0.8% maximum"
            },
            "discount": 2,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 5200,
            "purchaseCount": 2800,
            "supplierRating": 4.9,
            "deliveryTime": 1,
            "certifications": ["Ministry of Chemicals & Fertilizers Approved"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "fert_003",
            "name": "Potassium Nitrate (KNO3) - Coromandel International",
            "description": "Premium source of potassium and nitrogen for horticulture crops. Contains 13% nitrogen and 46% potassium with high solubility and no chloride.",
            "category": "fertilizers",
            "subcategory": "potassium_fertilizers",
            "brand": "Coromandel International",
            "tags": ["potassium_nitrate", "premium", "horticulture", "high_potassium", "no_chloride"],
            "cropType": ["vegetables", "fruits", "flowers", "spices"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 1200,
            "unit": "kg",
            "stock": 2000,
            "minOrderQuantity": 5,
            "maxOrderQuantity": 500,
            "images": ["/images/products/kno3-fertilizer.jpg"],
            "specifications": {
                "nitrogen_content": "13%",
                "potassium_content": "46%",
                "solubility": "Very high",
                "chloride_content": "0%",
                "application_rate": "200-300 kg/ha",
                "granule_size": "0.5-2.0 mm"
            },
            "discount": 5,
            "isActive": True,
            "isFeatured": False,
            "isTrending": True,
            "viewCount": 1200,
            "purchaseCount": 450,
            "supplierRating": 4.6,
            "deliveryTime": 3,
            "certifications": ["ISO Certified"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "fert_004",
            "name": "Ammonium Sulphate (AS) - Astro",
            "description": "Reliable source of nitrogen (21%) and sulphur (24%). Excellent for acid soils and sulphur-deficient regions with granular form for easy application.",
            "category": "fertilizers",
            "subcategory": "nitrogen_fertilizers",
            "brand": "Astro",
            "tags": ["ammonium_sulphate", "sulfur", "nitrogen", "acid_soils", "granular"],
            "cropType": ["rice", "wheat", "oilseeds", "vegetables", "tea"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 680,
            "unit": "bag_50kg",
            "stock": 3500,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 800,
            "images": ["/images/products/ammonium-sulphate.jpg"],
            "specifications": {
                "nitrogen_content": "21%",
                "sulphur_content": "24%",
                "solubility": "Highly soluble",
                "soil_type": "Acid soils",
                "application_rate": "75-150 kg/ha",
                "moisture_content": "1.0% maximum"
            },
            "discount": 4,
            "isActive": True,
            "isFeatured": True,
            "isTrending": False,
            "viewCount": 1600,
            "purchaseCount": 680,
            "supplierRating": 4.5,
            "deliveryTime": 2,
            "certifications": ["Ministry of Chemicals & Fertilizers Approved"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "fert_005",
            "name": "NPK (20:20:20) - Rashtriya Chemical & Fertilizers",
            "description": "Balanced nutrient formulation with equal proportion of nitrogen, phosphorus, and potassium. Ideal for balanced crop nutrition in all seasons.",
            "category": "fertilizers",
            "subcategory": "npk_fertilizers",
            "brand": "Rashtriya Chemical & Fertilizers",
            "tags": ["npk", "balanced", "granular", "all_crops", "micronutrients"],
            "cropType": ["all_crops"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 900,
            "unit": "bag_50kg",
            "stock": 4000,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 1000,
            "images": ["/images/products/npk-20-20-20.jpg"],
            "specifications": {
                "nitrogen_content": "20%",
                "phosphorus_content": "20%",
                "potassium_content": "20%",
                "micronutrients": "Fe, Zn, Cu, Mn, B",
                "application_rate": "100-150 kg/ha",
                "granule_size": "2-4 mm"
            },
            "discount": 6,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 2800,
            "purchaseCount": 1400,
            "supplierRating": 4.7,
            "deliveryTime": 2,
            "certifications": ["Ministry of Chemicals & Fertilizers Approved"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "fert_006",
            "name": "Zinc Sulphate (ZnSO4) - Agro Company",
            "description": "Essential micronutrient for overcoming zinc deficiency in crops. Highly effective for cereals and pulses with improved grain quality and yield.",
            "category": "fertilizers",
            "subcategory": "micronutrient_fertilizers",
            "brand": "Agro Company",
            "tags": ["zinc", "micronutrient", "zinc_deficiency", "cereal_crops", "heptahydrate"],
            "cropType": ["rice", "wheat", "corn", "pulses", "oilseeds"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 420,
            "unit": "kg",
            "stock": 1500,
            "minOrderQuantity": 5,
            "maxOrderQuantity": 300,
            "images": ["/images/products/zinc-sulphate.jpg"],
            "specifications": {
                "zinc_content": "21%",
                "sulphur_content": "11%",
                "water_solubility": "100%",
                "crystal_form": "Heptahydrate",
                "application_rate": "10-25 kg/ha",
                "particle_size": "0.5-1.5 mm"
            },
            "discount": 5,
            "isActive": True,
            "isFeatured": False,
            "isTrending": True,
            "viewCount": 900,
            "purchaseCount": 350,
            "supplierRating": 4.4,
            "deliveryTime": 3,
            "certifications": ["ISO Certified"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "fert_007",
            "name": "Muriate of Potash (MOP) - KRIBHCO",
            "description": "Primary source of potassium (60%) with chloride for crop nutrition. Improves crop color, taste and storability with enhanced disease resistance.",
            "category": "fertilizers",
            "subcategory": "potassium_fertilizers",
            "brand": "KRIBHCO",
            "tags": ["mop", "potassium", "potash", "granular", "high_potassium"],
            "cropType": ["rice", "wheat", "fruits", "vegetables", "spices"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 850,
            "unit": "bag_50kg",
            "stock": 3000,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 600,
            "images": ["/images/products/mop-fertilizer.jpg"],
            "specifications": {
                "potassium_content": "60%",
                "chloride_content": "47%",
                "solubility": "Highly soluble",
                "application_rate": "30-60 kg/ha",
                "moisture_content": "0.5% maximum",
                "granule_size": "1-3 mm"
            },
            "discount": 4,
            "isActive": True,
            "isFeatured": True,
            "isTrending": False,
            "viewCount": 1400,
            "purchaseCount": 650,
            "supplierRating": 4.6,
            "deliveryTime": 2,
            "certifications": ["Ministry of Chemicals & Fertilizers Approved"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "fert_008",
            "name": "Boron (Borax) - Godrej Agrevet",
            "description": "Important micronutrient for seed production and flowering in crops. Prevents hollow stem in vegetables and improves oil content in oilseeds.",
            "category": "fertilizers",
            "subcategory": "micronutrient_fertilizers",
            "brand": "Godrej Agrevet",
            "tags": ["boron", "borax", "micronutrient", "flowering", "seed_production"],
            "cropType": ["vegetables", "oilseeds", "fruits", "pulses"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 520,
            "unit": "kg",
            "stock": 800,
            "minOrderQuantity": 5,
            "maxOrderQuantity": 200,
            "images": ["/images/products/boron-borax.jpg"],
            "specifications": {
                "boron_content": "11%",
                "solubility": "Highly soluble",
                "crystal_form": "Pentahydrate",
                "application_rate": "1-2 kg/ha",
                "particle_size": "0.2-0.5 mm"
            },
            "discount": 6,
            "isActive": True,
            "isFeatured": False,
            "isTrending": False,
            "viewCount": 600,
            "purchaseCount": 200,
            "supplierRating": 4.3,
            "deliveryTime": 3,
            "certifications": ["ISO Certified"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "fert_009",
            "name": "Single Super Phosphate (SSP) - DCM Shriram",
            "description": "Rich source of phosphorus (16%) and calcium (21%) with sulphur content. Economical choice for phosphorus requirements with good soil availability.",
            "category": "fertilizers",
            "subcategory": "phosphate_fertilizers",
            "brand": "DCM Shriram",
            "tags": ["ssp", "phosphorus", "calcium", "sulfur", "cost_effective"],
            "cropType": ["rice", "wheat", "oilseeds", "pulses", "vegetables"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 580,
            "unit": "bag_50kg",
            "stock": 2500,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 800,
            "images": ["/images/products/ssp-fertilizer.jpg"],
            "specifications": {
                "phosphorus_content": "16%",
                "calcium_content": "21%",
                "sulphur_content": "11%",
                "solubility": "Moderately soluble",
                "application_rate": "125-250 kg/ha",
                "moisture_content": "5.0% maximum"
            },
            "discount": 3,
            "isActive": True,
            "isFeatured": False,
            "isTrending": False,
            "viewCount": 1100,
            "purchaseCount": 480,
            "supplierRating": 4.4,
            "deliveryTime": 2,
            "certifications": ["Ministry of Chemicals & Fertilizers Approved"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "fert_010",
            "name": "Neem Cake (Organic) - Kissan Agro",
            "description": "100% organic fertilizer from neem oil extraction residue. Contains nitrogen (4-5%) and acts as natural pesticide with soil conditioning properties.",
            "category": "fertilizers",
            "subcategory": "organic_fertilizers",
            "brand": "Kissan Agro",
            "tags": ["neem_cake", "organic", "natural", "pesticide", "soil_conditioner"],
            "cropType": ["all_crops", "vegetables", "fruits", "spices"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 450,
            "unit": "bag_25kg",
            "stock": 1200,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 400,
            "images": ["/images/products/neem-cake.jpg"],
            "specifications": {
                "nitrogen_content": "4-5%",
                "phosphorus_content": "0.5-1%",
                "potassium_content": "0.5-1%",
                "organic_matter": "85-90%",
                "application_rate": "500-1000 kg/ha",
                "moisture_content": "12% maximum"
            },
            "discount": 8,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 1500,
            "purchaseCount": 520,
            "supplierRating": 4.5,
            "deliveryTime": 4,
            "certifications": ["Certified Organic"],
            "warranty": "100% organic"
        }
    ],
    "pesticides": [
        {
            "id": "pest_001",
            "name": "Imidacloprid 17.8% SL - BASF",
            "description": "Systemic neonicotinoid insecticide for sucking pests control. Effective against aphids, whiteflies and thrips in vegetables and cereals with quick action.",
            "category": "pesticides",
            "subcategory": "insecticides",
            "brand": "BASF",
            "tags": ["imidacloprid", "neonicotinoid", "sucking_pests", "systemic", "quick_action"],
            "cropType": ["wheat", "rice", "cotton", "vegetables", "fruits"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 680,
            "unit": "litre",
            "stock": 800,
            "minOrderQuantity": 0.5,
            "maxOrderQuantity": 100,
            "images": ["/images/products/imidacloprid.jpg"],
            "specifications": {
                "active_ingredient": "Imidacloprid",
                "concentration": "17.8%",
                "formulation": "SL (Soluble Liquid)",
                "target_pests": "Aphids, Whiteflies, Thrips",
                "dosage": "150-200 ml/ha",
                "shelf_life": "3 years"
            },
            "discount": 5,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 1800,
            "purchaseCount": 620,
            "supplierRating": 4.7,
            "deliveryTime": 2,
            "certifications": ["IRAC Classification", "EPA Approved"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "pest_002",
            "name": "Chlorpyrifos 20% EC - Syngenta",
            "description": "Broad-spectrum organophosphate insecticide for chewing and sucking insect pests. Contact and stomach poison action for effective pest management.",
            "category": "pesticides",
            "subcategory": "insecticides",
            "brand": "Syngenta",
            "tags": ["chlorpyrifos", "organophosphate", "broad_spectrum", "contact_poison", "stomach_action"],
            "cropType": ["rice", "wheat", "cotton", "corn", "vegetables"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 520,
            "unit": "litre",
            "stock": 1200,
            "minOrderQuantity": 0.5,
            "maxOrderQuantity": 150,
            "images": ["/images/products/chlorpyrifos.jpg"],
            "specifications": {
                "active_ingredient": "Chlorpyrifos",
                "concentration": "20%",
                "formulation": "EC (Emulsifiable Concentrate)",
                "target_pests": "Stem Borers, Leaf Rollers, Armyworm",
                "dosage": "1000-1500 ml/ha",
                "shelf_life": "2 years"
            },
            "discount": 4,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 2100,
            "purchaseCount": 750,
            "supplierRating": 4.6,
            "deliveryTime": 2,
            "certifications": ["IRAC Classification", "EPA Approved"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "pest_003",
            "name": "Carbendazim 50% WP - Coromandel International",
            "description": "Systemic benzimidazole fungicide for managing fungal diseases. Provides protective and curative action against rice blast, sheath blight and powdery mildew.",
            "category": "pesticides",
            "subcategory": "fungicides",
            "brand": "Coromandel International",
            "tags": ["carbendazim", "fungicide", "systemic", "rice_blast", "powdery_mildew"],
            "cropType": ["rice", "wheat", "vegetables", "fruits", "cotton"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 450,
            "unit": "kg",
            "stock": 600,
            "minOrderQuantity": 0.5,
            "maxOrderQuantity": 80,
            "images": ["/images/products/carbendazim.jpg"],
            "specifications": {
                "active_ingredient": "Carbendazim",
                "concentration": "50%",
                "formulation": "WP (Wettable Powder)",
                "target_diseases": "Blast, Sheath Blight, Powdery Mildew",
                "dosage": "500-600 g/ha",
                "shelf_life": "3 years"
            },
            "discount": 6,
            "isActive": True,
            "isFeatured": False,
            "isTrending": True,
            "viewCount": 1200,
            "purchaseCount": 420,
            "supplierRating": 4.5,
            "deliveryTime": 3,
            "certifications": ["FRAC Classification"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "pest_004",
            "name": "Mancozeb 75% WP - Bayer CropScience",
            "description": "Preventive multi-site contact fungicide for vegetable and fruit crops. Excellent for managing leaf spot diseases and early blight with broad spectrum activity.",
            "category": "pesticides",
            "subcategory": "fungicides",
            "brand": "Bayer CropScience",
            "tags": ["mancozeb", "fungicide", "contact", "broad_spectrum", "early_blight"],
            "cropType": ["tomato", "potato", "grapes", "fruits", "vegetables"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 380,
            "unit": "kg",
            "stock": 900,
            "minOrderQuantity": 0.5,
            "maxOrderQuantity": 120,
            "images": ["/images/products/mancozeb.jpg"],
            "specifications": {
                "active_ingredient": "Mancozeb",
                "concentration": "75%",
                "formulation": "WP (Wettable Powder)",
                "target_diseases": "Early Blight, Leaf Spot, Late Blight",
                "dosage": "1.25-1.5 kg/ha",
                "shelf_life": "3 years"
            },
            "discount": 5,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 1500,
            "purchaseCount": 580,
            "supplierRating": 4.6,
            "deliveryTime": 2,
            "certifications": ["FRAC Classification"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "pest_005",
            "name": "Lambda-Cyhalothrin 5% EC - Rallis India",
            "description": "Pyrethroid synthetic insecticide with contact and stomach poison action. Highly effective against a wide range of insect pests in cereals and cotton.",
            "category": "pesticides",
            "subcategory": "insecticides",
            "brand": "Rallis India",
            "tags": ["lambda_cyhalothrin", "pyrethroid", "contact_poison", "broad_spectrum", "cotton"],
            "cropType": ["cotton", "rice", "wheat", "vegetables", "fruits"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 850,
            "unit": "litre",
            "stock": 700,
            "minOrderQuantity": 0.5,
            "maxOrderQuantity": 80,
            "images": ["/images/products/lambda-cyhalothrin.jpg"],
            "specifications": {
                "active_ingredient": "Lambda-Cyhalothrin",
                "concentration": "5%",
                "formulation": "EC (Emulsifiable Concentrate)",
                "target_pests": "Bollworms, Armyworm, Leaf Rollers",
                "dosage": "300-500 ml/ha",
                "shelf_life": "2 years"
            },
            "discount": 7,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 1600,
            "purchaseCount": 520,
            "supplierRating": 4.7,
            "deliveryTime": 3,
            "certifications": ["IRAC Classification"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "pest_006",
            "name": "Beauveria Bassiana (Organic) - Biosure",
            "description": "Bio-fungicide containing naturally occurring fungus spores. Safe for environment and human health while controlling white flies, scale insects and mites.",
            "category": "pesticides",
            "subcategory": "bio_pesticides",
            "brand": "Biosure",
            "tags": ["beauveria_bassiana", "bio_pesticide", "organic", "whiteflies", "eco_friendly"],
            "cropType": ["vegetables", "fruits", "cotton", "spices"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 580,
            "unit": "gram",
            "stock": 400,
            "minOrderQuantity": 50,
            "maxOrderQuantity": 50000,
            "images": ["/images/products/beauveria-bassiana.jpg"],
            "specifications": {
                "active_ingredient": "Beauveria Bassiana",
                "spore_count": "1-2 x 10^8 spores/ml",
                "formulation": "WP (Wettable Powder)",
                "target_pests": "Whiteflies, Scale Insects, Mites",
                "dosage": "200-500 g/ha",
                "shelf_life": "18 months"
            },
            "discount": 10,
            "isActive": True,
            "isFeatured": True,
            "isTrending": False,
            "viewCount": 800,
            "purchaseCount": 250,
            "supplierRating": 4.3,
            "deliveryTime": 4,
            "certifications": ["Certified Organic", "NPOP Approved"],
            "warranty": "100% organic"
        },
        {
            "id": "pest_007",
            "name": "Tricyclazole 75% WP - UPL Limited",
            "description": "Selective fungicide for rice blast management. Preventive action with excellent penetration into leaves for superior disease control.",
            "category": "pesticides",
            "subcategory": "fungicides",
            "brand": "UPL Limited",
            "tags": ["tricyclazole", "fungicide", "rice_blast", "preventive", "selective"],
            "cropType": ["rice"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 520,
            "unit": "kg",
            "stock": 500,
            "minOrderQuantity": 0.5,
            "maxOrderQuantity": 60,
            "images": ["/images/products/tricyclazole.jpg"],
            "specifications": {
                "active_ingredient": "Tricyclazole",
                "concentration": "75%",
                "formulation": "WP (Wettable Powder)",
                "target_diseases": "Rice Blast",
                "dosage": "750 g/ha",
                "shelf_life": "2 years"
            },
            "discount": 5,
            "isActive": True,
            "isFeatured": False,
            "isTrending": False,
            "viewCount": 900,
            "purchaseCount": 380,
            "supplierRating": 4.4,
            "deliveryTime": 3,
            "certifications": ["FRAC Classification"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "pest_008",
            "name": "Spinosad 45% SC - Godrej Agrevet",
            "description": "Natural organic insecticide derived from soil bacteria. Effective against Spodoptera (armyworm) and other caterpillar pests with safe residue profile.",
            "category": "pesticides",
            "subcategory": "bio_pesticides",
            "brand": "Godrej Agrevet",
            "tags": ["spinosad", "bio_pesticide", "natural", "armyworm", "organic"],
            "cropType": ["vegetables", "cotton", "fruits", "spices"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 920,
            "unit": "litre",
            "stock": 300,
            "minOrderQuantity": 0.5,
            "maxOrderQuantity": 50,
            "images": ["/images/products/spinosad.jpg"],
            "specifications": {
                "active_ingredient": "Spinosad",
                "concentration": "45%",
                "formulation": "SC (Suspension Concentrate)",
                "target_pests": "Armyworm, Caterpillars, Spodoptera",
                "dosage": "300-400 ml/ha",
                "shelf_life": "2 years"
            },
            "discount": 8,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 700,
            "purchaseCount": 200,
            "supplierRating": 4.5,
            "deliveryTime": 3,
            "certifications": ["Certified Organic", "NPOP Approved"],
            "warranty": "100% organic"
        },
        {
            "id": "pest_009",
            "name": "Profenofos 50% EC - Adama",
            "description": "Organophosphate insecticide for control of rice stem borers and leaf folders. Excellent knockdown effect with residual activity for sustained protection.",
            "category": "pesticides",
            "subcategory": "insecticides",
            "brand": "Adama",
            "tags": ["profenofos", "organophosphate", "stem_borers", "knockdown_effect", "rice"],
            "cropType": ["rice", "vegetables", "fruits"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 480,
            "unit": "litre",
            "stock": 1000,
            "minOrderQuantity": 0.5,
            "maxOrderQuantity": 200,
            "images": ["/images/products/profenofos.jpg"],
            "specifications": {
                "active_ingredient": "Profenofos",
                "concentration": "50%",
                "formulation": "EC (Emulsifiable Concentrate)",
                "target_pests": "Stem Borers, Leaf Folders, Thrips",
                "dosage": "500-750 ml/ha",
                "shelf_life": "2 years"
            },
            "discount": 4,
            "isActive": True,
            "isFeatured": False,
            "isTrending": False,
            "viewCount": 1100,
            "purchaseCount": 450,
            "supplierRating": 4.4,
            "deliveryTime": 2,
            "certifications": ["IRAC Classification"],
            "warranty": "Quality guaranteed"
        },
        {
            "id": "pest_010",
            "name": "Sulfur 80% WP - Sulfex",
            "description": "Elemental sulfur powder for fungal disease management. Non-toxic alternative for controlling powdery mildew and mites with protective and curative action.",
            "category": "pesticides",
            "subcategory": "fungicides",
            "brand": "Sulfex",
            "tags": ["sulfur", "elemental", "powdery_mildew", "non_toxic", "natural"],
            "cropType": ["grapes", "vegetables", "fruits", "spices"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 220,
            "unit": "kg",
            "stock": 2000,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 500,
            "images": ["/images/products/sulfur-powder.jpg"],
            "specifications": {
                "active_ingredient": "Elemental Sulfur",
                "concentration": "80%",
                "formulation": "WP (Wettable Powder)",
                "target_diseases": "Powdery Mildew, Red Spider Mites",
                "dosage": "3-5 kg/ha",
                "shelf_life": "3 years"
            },
            "discount": 3,
            "isActive": True,
            "isFeatured": False,
            "isTrending": True,
            "viewCount": 1300,
            "purchaseCount": 650,
            "supplierRating": 4.3,
            "deliveryTime": 2,
            "certifications": ["Certified Organic"],
            "warranty": "100% natural"
        }
    ],
    "equipment": [
        {
            "id": "equip_001",
            "name": "TAFE 9055 Tractor - 55 HP Compact Utility",
            "description": "Reliable compact utility tractor with 55 HP power suitable for medium-sized farms. Strong transmission, comfortable cabin and excellent fuel efficiency for all farming operations.",
            "category": "equipment",
            "subcategory": "tractors",
            "brand": "TAFE (Tractors and Farm Equipment)",
            "tags": ["tractor", "55_hp", "compact_utility", "fuel_efficient", "reliable"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 650000,
            "unit": "unit",
            "stock": 45,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 10,
            "images": ["/images/products/tafe-9055.jpg"],
            "specifications": {
                "horsepower": "55 HP",
                "transmission": "12 Forward + 3 Reverse",
                "fuel_tank_capacity": "65 litres",
                "ground_clearance": "315 mm",
                "turning_radius": "3.2 m",
                "hydraulic_lift_capacity": "2000 kg"
            },
            "discount": 5,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 2500,
            "purchaseCount": 280,
            "supplierRating": 4.7,
            "deliveryTime": 30,
            "certifications": ["SIAM Certified", "VAHAN Registered"],
            "warranty": "2 years comprehensive"
        },
        {
            "id": "equip_002",
            "name": "Preet 987 Combine Harvester",
            "description": "All-purpose combine harvester for wheat and paddy. Advanced threshing system with high efficiency separation for minimal grain losses and superior output.",
            "category": "equipment",
            "subcategory": "harvesters",
            "brand": "Preet",
            "tags": ["combine_harvester", "wheat", "paddy", "high_efficiency", "advanced"],
            "region": ["north_india", "punjab", "haryana"],
            "seasonal": True,
            "seasonStart": "april",
            "seasonEnd": "october",
            "basePrice": 1200000,
            "unit": "unit",
            "stock": 25,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 5,
            "images": ["/images/products/preet-987-harvester.jpg"],
            "specifications": {
                "engine_power": "42 HP Diesel",
                "cutting_width": "1.8 m",
                "tank_capacity": "120 litres",
                "separation_system": "Advanced Threshing",
                "grain_tank_capacity": "2500 kg",
                "operation_capacity": "1.5-2.0 hectares/hour"
            },
            "discount": 8,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 1800,
            "purchaseCount": 150,
            "supplierRating": 4.6,
            "deliveryTime": 45,
            "certifications": ["SIAM Certified", "Emission Compliant"],
            "warranty": "2 years comprehensive"
        },
        {
            "id": "equip_003",
            "name": "Mahindra 585 DI Tractor - 58 HP",
            "description": "Advanced diesel injection tractor with superior torque and fuel economy. Perfect for general farming with strong hydraulic system and spacious cabin.",
            "category": "equipment",
            "subcategory": "tractors",
            "brand": "Mahindra",
            "tags": ["tractor", "58_hp", "diesel_injection", "fuel_economy", "hydraulic"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 720000,
            "unit": "unit",
            "stock": 60,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 15,
            "images": ["/images/products/mahindra-585-di.jpg"],
            "specifications": {
                "horsepower": "58 HP",
                "transmission": "12 Forward + 3 Reverse",
                "fuel_tank_capacity": "70 litres",
                "ground_clearance": "320 mm",
                "turning_radius": "3.4 m",
                "hydraulic_lift_capacity": "2500 kg"
            },
            "discount": 6,
            "isActive": True,
            "isFeatured": True,
            "isTrending": False,
            "viewCount": 2000,
            "purchaseCount": 320,
            "supplierRating": 4.8,
            "deliveryTime": 30,
            "certifications": ["SIAM Certified", "VAHAN Registered"],
            "warranty": "2 years comprehensive"
        },
        {
            "id": "equip_004",
            "name": "John Deere CP690 Combine Harvester",
            "description": "Premium combine harvester with cutting-edge technology for uniform grain collection. Advanced cleaning system with minimal losses for optimal grain quality.",
            "category": "equipment",
            "subcategory": "harvesters",
            "brand": "John Deere",
            "tags": ["combine_harvester", "premium", "advanced_technology", "grain_quality", "efficient"],
            "region": ["all_india"],
            "seasonal": True,
            "seasonStart": "march",
            "seasonEnd": "november",
            "basePrice": 1800000,
            "unit": "unit",
            "stock": 15,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 3,
            "images": ["/images/products/john-deere-cp690.jpg"],
            "specifications": {
                "engine_power": "58 HP",
                "cutting_width": "2.1 m",
                "tank_capacity": "140 litres",
                "grain_tank_capacity": "3500 kg",
                "operation_capacity": "2.0-2.5 hectares/hour",
                "cleaning_efficiency": "95%+"
            },
            "discount": 10,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 1200,
            "purchaseCount": 80,
            "supplierRating": 4.8,
            "deliveryTime": 60,
            "certifications": ["SIAM Certified", "International Standards"],
            "warranty": "3 years comprehensive"
        },
        {
            "id": "equip_005",
            "name": "Rotavator (Rotary Tiller) - 6 Feet",
            "description": "Heavy-duty rotavator for soil preparation and mixing. Suitable for all soil conditions with adjustable depth control for uniform soil preparation.",
            "category": "equipment",
            "subcategory": "farm_implements",
            "brand": "Standard Agricultural",
            "tags": ["rotavator", "soil_preparation", "tilling", "6_feet", "adjustable_depth"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 85000,
            "unit": "unit",
            "stock": 120,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 50,
            "images": ["/images/products/rotavator-6ft.jpg"],
            "specifications": {
                "working_width": "6 feet",
                "tiller_depth": "0-6 inches adjustable",
                "power_requirement": "35-45 HP tractor",
                "number_of_tines": "18-20",
                "tiller_speed": "50-60 RPM",
                "weight": "600 kg"
            },
            "discount": 4,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 1500,
            "purchaseCount": 420,
            "supplierRating": 4.5,
            "deliveryTime": 7,
            "certifications": ["Quality Assured"],
            "warranty": "1 year"
        },
        {
            "id": "equip_006",
            "name": "Drip Irrigation System - 1 Hectare Kit",
            "description": "Complete automated drip irrigation system with drip lines and connectors. Efficient water usage with uniform moisture distribution for increased yield.",
            "category": "equipment",
            "subcategory": "irrigation_equipment",
            "brand": "Jain Irrigation",
            "tags": ["drip_irrigation", "water_efficient", "automation", "1_hectare", "uniform_moisture"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 45000,
            "unit": "kit",
            "stock": 200,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 100,
            "images": ["/images/products/drip-irrigation-kit.jpg"],
            "specifications": {
                "coverage_area": "1 hectare",
                "drip_line_spacing": "60-75 cm",
                "dripper_spacing": "30-45 cm",
                "water_pressure": "1-2.5 kg/cm2",
                "flow_rate": "1-4 litres/hour per dripper",
                "pipe_thickness": "0.75-1.0 mm"
            },
            "discount": 7,
            "isActive": True,
            "isFeatured": False,
            "isTrending": True,
            "viewCount": 1200,
            "purchaseCount": 350,
            "supplierRating": 4.6,
            "deliveryTime": 5,
            "certifications": ["ISO Certified"],
            "warranty": "2 years"
        },
        {
            "id": "equip_007",
            "name": "Diesel Sprayer Pump - 1600 Watt",
            "description": "Powerful diesel-powered sprayer for large-scale pesticide application. Consistent pressure output with wide spray pattern for efficient coverage.",
            "category": "equipment",
            "subcategory": "sprayers",
            "brand": "Agrox",
            "tags": ["diesel_sprayer", "1600_watt", "pesticide_application", "large_farm", "powerful"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 28000,
            "unit": "unit",
            "stock": 80,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 30,
            "images": ["/images/products/diesel-sprayer.jpg"],
            "specifications": {
                "power": "1600 Watt",
                "tank_capacity": "150 litres",
                "spray_pressure": "40 PSI",
                "nozzle_type": "Adjustable Fan",
                "spray_width": "12-15 feet",
                "engine_type": "4-stroke Diesel"
            },
            "discount": 5,
            "isActive": True,
            "isFeatured": False,
            "isTrending": False,
            "viewCount": 900,
            "purchaseCount": 280,
            "supplierRating": 4.4,
            "deliveryTime": 3,
            "certifications": ["Quality Assured"],
            "warranty": "1 year"
        },
        {
            "id": "equip_008",
            "name": "Manual Operated Crop Cutter - Sickle Type",
            "description": "Traditional manual crop cutter with sharp blade for efficient cutting. Lightweight design for comfortable operation during harvesting season.",
            "category": "equipment",
            "subcategory": "hand_tools",
            "brand": "Basic Tools",
            "tags": ["crop_cutter", "manual", "sickle_type", "lightweight", "traditional"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 450,
            "unit": "unit",
            "stock": 1000,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 500,
            "images": ["/images/products/crop-cutter.jpg"],
            "specifications": {
                "blade_length": "8 inches",
                "blade_material": "High Carbon Steel",
                "handle_material": "Wood",
                "handle_length": "4 feet",
                "weight": "1.2 kg",
                "blade_sharpness": "Factory sharpened"
            },
            "discount": 3,
            "isActive": True,
            "isFeatured": False,
            "isTrending": False,
            "viewCount": 600,
            "purchaseCount": 850,
            "supplierRating": 4.2,
            "deliveryTime": 2,
            "certifications": ["Safety Certified"],
            "warranty": "6 months"
        },
        {
            "id": "equip_009",
            "name": "Seed Drill Machine - 9 Row Tractor Mounted",
            "description": "Precision seed drill for uniform seed placement and spacing. Adjustable depth control with multiple hopper for different seed types.",
            "category": "equipment",
            "subcategory": "sowing_equipment",
            "brand": "AgroDrill",
            "tags": ["seed_drill", "9_row", "precision_sowing", "adjustable_depth", "tractor_mounted"],
            "region": ["all_india"],
            "seasonal": True,
            "seasonStart": "june",
            "seasonEnd": "december",
            "basePrice": 65000,
            "unit": "unit",
            "stock": 90,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 40,
            "images": ["/images/products/seed-drill-9row.jpg"],
            "specifications": {
                "number_of_rows": "9",
                "seed_spacing": "15-25 cm adjustable",
                "row_spacing": "20 cm",
                "hopper_capacity": "50 litres",
                "power_requirement": "25-35 HP tractor",
                "sowing_depth": "3-7 cm adjustable"
            },
            "discount": 6,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 1100,
            "purchaseCount": 320,
            "supplierRating": 4.5,
            "deliveryTime": 10,
            "certifications": ["Quality Assured"],
            "warranty": "1 year"
        },
        {
            "id": "equip_010",
            "name": "Cultivator (Hoe) - 5 Tine Tractor Mounted",
            "description": "Multi-purpose cultivator for inter-row cultivation and weed removal. Rigid frame with replaceable tines for long-lasting performance.",
            "category": "equipment",
            "subcategory": "farm_implements",
            "brand": "Standard Agricultural",
            "tags": ["cultivator", "5_tine", "inter_row_cultivation", "weed_control", "rigid_frame"],
            "region": ["all_india"],
            "seasonal": False,
            "basePrice": 18000,
            "unit": "unit",
            "stock": 200,
            "minOrderQuantity": 1,
            "maxOrderQuantity": 80,
            "images": ["/images/products/cultivator-5tine.jpg"],
            "specifications": {
                "number_of_tines": "5",
                "working_width": "1.5 m",
                "tine_spacing": "30 cm",
                "cultivation_depth": "5-8 inches adjustable",
                "power_requirement": "20-30 HP tractor",
                "weight": "350 kg"
            },
            "discount": 4,
            "isActive": True,
            "isFeatured": False,
            "isTrending": False,
            "viewCount": 800,
            "purchaseCount": 240,
            "supplierRating": 4.3,
            "deliveryTime": 5,
            "certifications": ["Quality Assured"],
            "warranty": "1 year"
        }
    ],
    "produce": [
        {
            "id": "prod_001",
            "name": "Tomato (Hybrid) - Fresh Market Quality",
            "description": "Fresh, high-quality hybrid tomatoes suitable for table and processing. Rich red color with firm texture and excellent taste.",
            "category": "produce",
            "subcategory": "vegetables",
            "brand": "Farmer Direct",
            "tags": ["tomato", "hybrid", "fresh", "red", "local"],
            "cropType": ["tomato"],
            "region": ["maharashtra", "karnataka", "tamil_nadu"],
            "seasonal": True,
            "seasonStart": "october",
            "seasonEnd": "march",
            "basePrice": 35,
            "unit": "kg",
            "stock": 5000,
            "minOrderQuantity": 5,
            "maxOrderQuantity": 1000,
            "images": ["/images/products/tomato-fresh.jpg"],
            "specifications": {
                "size": "Medium (80-100g each)",
                "color": "Bright Red",
                "texture": "Firm",
                "shelf_life": "7-10 days at room temperature",
                "moisture_content": "94-95%",
                "ph_level": "4.2-4.5"
            },
            "discount": 5,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 3500,
            "purchaseCount": 2100,
            "supplierRating": 4.7,
            "deliveryTime": 1,
            "certifications": ["Fresh Produce Certified"],
            "warranty": "Fresh guarantee"
        },
        {
            "id": "prod_002",
            "name": "Onion - Red/Pink Variety",
            "description": "Premium quality red onions with strong flavor and good storage capability. Ideal for culinary use and export quality standards.",
            "category": "produce",
            "subcategory": "vegetables",
            "brand": "Farmer Direct",
            "tags": ["onion", "red", "storage_stable", "flavor", "premium"],
            "cropType": ["onion"],
            "region": ["maharashtra", "andhra_pradesh", "karnataka"],
            "seasonal": True,
            "seasonStart": "september",
            "seasonEnd": "may",
            "basePrice": 25,
            "unit": "kg",
            "stock": 8000,
            "minOrderQuantity": 10,
            "maxOrderQuantity": 2000,
            "images": ["/images/products/onion-red.jpg"],
            "specifications": {
                "size": "Medium (120-150g each)",
                "color": "Deep Red/Pink",
                "storage_life": "6-8 months at cool storage",
                "pungency": "High",
                "dry_matter": "12-14%",
                "respiration_rate": "Low"
            },
            "discount": 3,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 4200,
            "purchaseCount": 2800,
            "supplierRating": 4.8,
            "deliveryTime": 1,
            "certifications": ["Fresh Produce Certified"],
            "warranty": "Fresh guarantee"
        },
        {
            "id": "prod_003",
            "name": "Potato (White) - Fresh Harvest",
            "description": "Premium quality white potatoes perfect for cooking. Uniform size with good nutritional content and extended storage life.",
            "category": "produce",
            "subcategory": "vegetables",
            "brand": "Farmer Direct",
            "tags": ["potato", "white", "fresh", "storage", "cooking"],
            "cropType": ["potato"],
            "region": ["himachal_pradesh", "punjab", "uttar_pradesh"],
            "seasonal": True,
            "seasonStart": "september",
            "seasonEnd": "march",
            "basePrice": 20,
            "unit": "kg",
            "stock": 12000,
            "minOrderQuantity": 20,
            "maxOrderQuantity": 3000,
            "images": ["/images/products/potato-white.jpg"],
            "specifications": {
                "size": "Medium (150-200g each)",
                "color": "White/Cream",
                "storage_life": "8-10 months at cold storage",
                "starch_content": "15-18%",
                "dry_matter": "18-20%",
                "cooking_quality": "Excellent"
            },
            "discount": 4,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 3800,
            "purchaseCount": 2600,
            "supplierRating": 4.7,
            "deliveryTime": 1,
            "certifications": ["Fresh Produce Certified"],
            "warranty": "Fresh guarantee"
        },
        {
            "id": "prod_004",
            "name": "Bell Pepper (Capsicum) - Hybrid",
            "description": "Vibrant colored bell peppers with thick walls and sweet taste. Available in red, green, and yellow varieties.",
            "category": "produce",
            "subcategory": "vegetables",
            "brand": "Farmer Direct",
            "tags": ["capsicum", "bell_pepper", "hybrid", "colorful", "sweet"],
            "cropType": ["capsicum"],
            "region": ["karnataka", "maharashtra", "tamil_nadu"],
            "seasonal": True,
            "seasonStart": "october",
            "seasonEnd": "march",
            "basePrice": 60,
            "unit": "kg",
            "stock": 2000,
            "minOrderQuantity": 5,
            "maxOrderQuantity": 500,
            "images": ["/images/products/bell-pepper.jpg"],
            "specifications": {
                "size": "Large (200-250g each)",
                "color": "Red/Green/Yellow",
                "texture": "Firm, Thick Wall",
                "shelf_life": "14-21 days at 10°C",
                "moisture_content": "92%",
                "vitamin_c": "High"
            },
            "discount": 6,
            "isActive": True,
            "isFeatured": False,
            "isTrending": True,
            "viewCount": 1500,
            "purchaseCount": 650,
            "supplierRating": 4.6,
            "deliveryTime": 1,
            "certifications": ["Fresh Produce Certified"],
            "warranty": "Fresh guarantee"
        },
        {
            "id": "prod_005",
            "name": "Brinjal (Eggplant) - Long Variety",
            "description": "Fresh long brinjal with purple color and tender texture. Ideal for dry curry preparations and grilling with uniform quality.",
            "category": "produce",
            "subcategory": "vegetables",
            "brand": "Farmer Direct",
            "tags": ["brinjal", "eggplant", "long_variety", "purple", "tender"],
            "cropType": ["brinjal"],
            "region": ["maharashtra", "karnataka", "odisha"],
            "seasonal": True,
            "seasonStart": "march",
            "seasonEnd": "november",
            "basePrice": 40,
            "unit": "kg",
            "stock": 1500,
            "minOrderQuantity": 5,
            "maxOrderQuantity": 400,
            "images": ["/images/products/brinjal.jpg"],
            "specifications": {
                "size": "Long (25-30 cm)",
                "color": "Purple/Deep Purple",
                "texture": "Tender",
                "shelf_life": "7-10 days at room temperature",
                "moisture_content": "92%",
                "seeds_content": "Minimal"
            },
            "discount": 5,
            "isActive": True,
            "isFeatured": False,
            "isTrending": False,
            "viewCount": 900,
            "purchaseCount": 380,
            "supplierRating": 4.5,
            "deliveryTime": 1,
            "certifications": ["Fresh Produce Certified"],
            "warranty": "Fresh guarantee"
        },
        {
            "id": "prod_006",
            "name": "Cucumber (Hybrid) - Fresh",
            "description": "Crunchy hybrid cucumbers with thin skin and minimal seeds. Perfect for salads and pickles with uniform size and quality.",
            "category": "produce",
            "subcategory": "vegetables",
            "brand": "Farmer Direct",
            "tags": ["cucumber", "hybrid", "crunchy", "minimal_seeds", "salad"],
            "cropType": ["cucumber"],
            "region": ["maharashtra", "karnataka", "tamil_nadu"],
            "seasonal": True,
            "seasonStart": "march",
            "seasonEnd": "september",
            "basePrice": 32,
            "unit": "kg",
            "stock": 2500,
            "minOrderQuantity": 5,
            "maxOrderQuantity": 600,
            "images": ["/images/products/cucumber-hybrid.jpg"],
            "specifications": {
                "size": "Medium (20-25 cm)",
                "color": "Dark Green",
                "texture": "Crunchy",
                "shelf_life": "7-10 days at 10°C",
                "moisture_content": "96%",
                "seeds": "Minimal"
            },
            "discount": 4,
            "isActive": True,
            "isFeatured": False,
            "isTrending": True,
            "viewCount": 1200,
            "purchaseCount": 520,
            "supplierRating": 4.5,
            "deliveryTime": 1,
            "certifications": ["Fresh Produce Certified"],
            "warranty": "Fresh guarantee"
        },
        {
            "id": "prod_007",
            "name": "Okra (Ladies Finger) - Fresh Green",
            "description": "Fresh, tender okra with vibrant green color. Premium quality for vegetable markets with high culinary and medicinal value.",
            "category": "produce",
            "subcategory": "vegetables",
            "brand": "Farmer Direct",
            "tags": ["okra", "ladies_finger", "tender", "green", "fresh"],
            "cropType": ["okra"],
            "region": ["maharashtra", "karnataka", "andhra_pradesh"],
            "seasonal": True,
            "seasonStart": "march",
            "seasonEnd": "october",
            "basePrice": 45,
            "unit": "kg",
            "stock": 1200,
            "minOrderQuantity": 5,
            "maxOrderQuantity": 300,
            "images": ["/images/products/okra-fresh.jpg"],
            "specifications": {
                "size": "Small-Medium (10-12 cm)",
                "color": "Bright Green",
                "texture": "Tender, Non-Sticky",
                "shelf_life": "3-4 days at room temperature",
                "moisture_content": "90%",
                "fiber_content": "Low"
            },
            "discount": 7,
            "isActive": True,
            "isFeatured": False,
            "isTrending": False,
            "viewCount": 650,
            "purchaseCount": 280,
            "supplierRating": 4.4,
            "deliveryTime": 1,
            "certifications": ["Fresh Produce Certified"],
            "warranty": "Fresh guarantee"
        },
        {
            "id": "prod_008",
            "name": "Spinach (Palak) - Fresh Leaves",
            "description": "Fresh organic spinach leaves with high nutritional value. Tender greens perfect for salads and cooking with excellent iron content.",
            "category": "produce",
            "subcategory": "leafy_vegetables",
            "brand": "Farmer Direct",
            "tags": ["spinach", "palak", "leafy_greens", "organic", "nutritious"],
            "cropType": ["spinach"],
            "region": ["punjab", "haryana", "uttar_pradesh"],
            "seasonal": True,
            "seasonStart": "october",
            "seasonEnd": "march",
            "basePrice": 28,
            "unit": "kg",
            "stock": 800,
            "minOrderQuantity": 3,
            "maxOrderQuantity": 300,
            "images": ["/images/products/spinach-palak.jpg"],
            "specifications": {
                "color": "Dark Green",
                "texture": "Tender, Crisp",
                "shelf_life": "3-5 days at 4°C",
                "moisture_content": "91%",
                "iron_content": "High",
                "pesticide_residue": "None (Organic)"
            },
            "discount": 8,
            "isActive": True,
            "isFeatured": True,
            "isTrending": True,
            "viewCount": 1100,
            "purchaseCount": 420,
            "supplierRating": 4.6,
            "deliveryTime": 1,
            "certifications": ["Certified Organic", "Fresh Produce"],
            "warranty": "Fresh guarantee"
        },
        {
            "id": "prod_009",
            "name": "Carrot (Orange) - Fresh Premium",
            "description": "Bright orange carrots with high beta-carotene content. Perfect for cooking, juicing and raw consumption with good storage life.",
            "category": "produce",
            "subcategory": "root_vegetables",
            "brand": "Farmer Direct",
            "tags": ["carrot", "orange", "beta_carotene", "fresh", "storage"],
            "cropType": ["carrot"],
            "region": ["punjab", "himachal_pradesh", "jammu_kashmir"],
            "seasonal": True,
            "seasonStart": "september",
            "seasonEnd": "march",
            "basePrice": 30,
            "unit": "kg",
            "stock": 3500,
            "minOrderQuantity": 5,
            "maxOrderQuantity": 800,
            "images": ["/images/products/carrot-orange.jpg"],
            "specifications": {
                "size": "Medium (150-200g each)",
                "color": "Bright Orange",
                "texture": "Crisp, Juicy",
                "shelf_life": "15-20 days at 4°C",
                "moisture_content": "88%",
                "sweetness": "High"
            },
            "discount": 5,
            "isActive": True,
            "isFeatured": True,
            "isTrending": False,
            "viewCount": 1300,
            "purchaseCount": 680,
            "supplierRating": 4.5,
            "deliveryTime": 1,
            "certifications": ["Fresh Produce Certified"],
            "warranty": "Fresh guarantee"
        },
        {
            "id": "prod_010",
            "name": "Green Peas (Matar) - Fresh Pods",
            "description": "Fresh green peas in tender pods with sweet taste. Premium quality for cooking and frozen processing with good nutritional profile.",
            "category": "produce",
            "subcategory": "legume_vegetables",
            "brand": "Farmer Direct",
            "tags": ["peas", "matar", "green", "sweet", "fresh_pods"],
            "cropType": ["peas"],
            "region": ["punjab", "haryana", "himachal_pradesh"],
            "seasonal": True,
            "seasonStart": "october",
            "seasonEnd": "march",
            "basePrice": 50,
            "unit": "kg",
            "stock": 1000,
            "minOrderQuantity": 5,
            "maxOrderQuantity": 300,
            "images": ["/images/products/peas-green.jpg"],
            "specifications": {
                "pod_length": "8-10 cm",
                "pea_size": "Medium",
                "color": "Bright Green",
                "sweetness": "High TSS (8-9%)",
                "shelf_life": "7-10 days at 4°C",
                "protein_content": "High"
            },
            "discount": 6,
            "isActive": True,
            "isFeatured": False,
            "isTrending": True,
            "viewCount": 900,
            "purchaseCount": 380,
            "supplierRating": 4.6,
            "deliveryTime": 1,
            "certifications": ["Fresh Produce Certified"],
            "warranty": "Fresh guarantee"
        }
    ]
}

# Save to CSV for database import
import pandas as pd

# Flatten data for CSV
all_products = []
for category, products in agricultural_database.items():
    for product in products:
        product_row = {
            'id': product['id'],
            'name': product['name'],
            'category': product['category'],
            'subcategory': product.get('subcategory', ''),
            'brand': product['brand'],
            'basePrice': product['basePrice'],
            'unit': product['unit'],
            'stock': product['stock'],
            'discount': product['discount'],
            'supplierRating': product['supplierRating'],
            'isFeatured': product['isFeatured'],
            'isTrending': product['isTrending']
        }
        all_products.append(product_row)

df = pd.DataFrame(all_products)
df.to_csv('agricultural_products_sample.csv', index=False)

print(f"✓ Database Created Successfully!")
print(f"\nTotal Products Created: {len(all_products)}")
print(f"\nCategory Distribution:")
for cat in agricultural_database.keys():
    count = len(agricultural_database[cat])
    print(f"  • {cat.upper()}: {count} products")

print(f"\nSample CSV Preview:")
print(df.head(12).to_string())
