import React, { useEffect, useState } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { FiCheckCircle, FiArrowRight, FiDownload, FiShare2, FiCalendar } from 'react-icons/fi';
import './ApplicationSuccess.css';

const ApplicationSuccess = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const [applicationData, setApplicationData] = useState(null);

  useEffect(() => {
    // Get application data from location state or localStorage
    const data = location.state?.applicationData;
    if (data) {
      setApplicationData(data);
      // Store in localStorage for persistence
      localStorage.setItem('lastApplication', JSON.stringify(data));
    } else {
      // Try to get from localStorage
      const stored = localStorage.getItem('lastApplication');
      if (stored) {
        setApplicationData(JSON.parse(stored));
      }
    }
  }, [location.state]);

  const handleViewStatus = () => {
    if (applicationData?.applicationId) {
      navigate(`/schemes/application/${applicationData.applicationId}`);
    }
  };

  const handleShareApplication = () => {
    if (navigator.share && applicationData) {
      navigator.share({
        title: 'Scheme Application Submitted',
        text: `I have successfully applied for ${applicationData.schemeName || 'Government Scheme'}. Application ID: ${applicationData.applicationId}`,
        url: window.location.href
      });
    } else {
      // Fallback: copy to clipboard
      const text = `Application submitted successfully! Application ID: ${applicationData?.applicationId}`;
      navigator.clipboard.writeText(text);
      alert('Application details copied to clipboard!');
    }
  };

  const handleDownloadReceipt = () => {
    // Create a simple receipt
    const receiptContent = `
AGROUNIFY - SCHEME APPLICATION RECEIPT
=====================================

Application ID: ${applicationData?.applicationId || 'N/A'}
Submitted Date: ${new Date().toLocaleDateString('en-IN')}
Scheme: ${applicationData?.schemeName || 'Government Scheme'}

Status: Application Submitted Successfully

Next Steps:
${applicationData?.nextSteps?.map(step => `- ${step.step}: ${step.description}`).join('\n') || 'Please check application status for updates'}

Keep this Application ID for future reference.
You will receive updates via SMS/email.

Generated by AgroUnify
${new Date().toLocaleString('en-IN')}
    `;

    const blob = new Blob([receiptContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `application-receipt-${applicationData?.applicationId || 'unknown'}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (!applicationData) {
    return (
      <div className="application-success-page">
        <div className="container">
          <div className="error">
            <h2>No Application Data Found</h2>
            <p>Please submit an application first.</p>
            <button
              className="btn btn-primary"
              onClick={() => navigate('/schemes')}
            >
              Browse Schemes
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="application-success-page">
      <div className="container">
        {/* Success Header */}
        <div className="success-header">
          <div className="success-icon">
            <FiCheckCircle />
          </div>
          <h1>🎉 Application Submitted Successfully!</h1>
          <p>Your government scheme application has been received and is being processed.</p>
        </div>

        {/* Application Summary */}
        <div className="application-summary">
          <div className="summary-card">
            <h2>Application Details</h2>
            <div className="summary-content">
              <div className="summary-row">
                <span className="label">Application ID:</span>
                <span className="value highlight">{applicationData.applicationId}</span>
              </div>
              <div className="summary-row">
                <span className="label">Scheme:</span>
                <span className="value">{applicationData.schemeName || 'Government Scheme'}</span>
              </div>
              <div className="summary-row">
                <span className="label">Submitted:</span>
                <span className="value">{new Date().toLocaleDateString('en-IN')}</span>
              </div>
              <div className="summary-row">
                <span className="label">Status:</span>
                <span className="value status-submitted">Submitted</span>
              </div>
            </div>
          </div>
        </div>

        {/* Next Steps */}
        {applicationData.nextSteps && applicationData.nextSteps.length > 0 && (
          <div className="next-steps-section">
            <h2>📋 What Happens Next?</h2>
            <div className="steps-grid">
              {applicationData.nextSteps.map((step, index) => (
                <div key={index} className="step-card">
                  <div className="step-number">{index + 1}</div>
                  <div className="step-content">
                    <h3>{step.step}</h3>
                    <p>{step.description}</p>
                    {step.deadline && (
                      <div className="step-deadline">
                        <FiCalendar />
                        <span>Expected by: {new Date(step.deadline).toLocaleDateString('en-IN')}</span>
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Important Information */}
        <div className="info-section">
          <h2>ℹ️ Important Information</h2>
          <div className="info-cards">
            <div className="info-card">
              <div className="info-icon">📱</div>
              <div className="info-content">
                <h3>SMS Updates</h3>
                <p>You will receive SMS updates on your registered mobile number about application status.</p>
              </div>
            </div>
            <div className="info-card">
              <div className="info-icon">📧</div>
              <div className="info-content">
                <h3>Email Confirmation</h3>
                <p>A confirmation email has been sent with your application details and next steps.</p>
              </div>
            </div>
            <div className="info-card">
              <div className="info-icon">⏰</div>
              <div className="info-content">
                <h3>Processing Time</h3>
                <p>Initial verification usually takes 7-10 working days. You can track status anytime.</p>
              </div>
            </div>
            <div className="info-card">
              <div className="info-icon">📞</div>
              <div className="info-content">
                <h3>Need Help?</h3>
                <p>Contact the scheme helpline or visit your nearest agriculture office for assistance.</p>
              </div>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="action-buttons">
          <button
            className="btn btn-primary"
            onClick={handleViewStatus}
          >
            <FiArrowRight />
            Track Application Status
          </button>
          <button
            className="btn btn-secondary"
            onClick={handleDownloadReceipt}
          >
            <FiDownload />
            Download Receipt
          </button>
          <button
            className="btn btn-outline"
            onClick={handleShareApplication}
          >
            <FiShare2 />
            Share
          </button>
        </div>

        {/* Additional Actions */}
        <div className="additional-actions">
          <p>Want to apply for more schemes?</p>
          <button
            className="btn btn-link"
            onClick={() => navigate('/schemes')}
          >
            Browse More Government Schemes →
          </button>
        </div>
      </div>
    </div>
  );
};

export default ApplicationSuccess;